### ISSUE TITLE
raz_create_mbd_tree_file must be renamed and return all the names of all files it creates

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#107]
Currently, `raz_create_mbd_tree_file` creates two files (a tree and L matrix) and returns the name of one file.

Better would be to make the name reflect what the function does, and let the function do as such:

  1.  Rename to `raz_create_mbd_tree_files` to indicate multiple files are created
  2. Return both filenames
  3. Update the tests to verify indeed two files are returned, that both exist

**Comment by richelbilderbeek** [comment]
Let's see who assigns himself the Issue first...

**Comment by Giappo** [comment]
We currently have no way to produce an L table for the bd tree.
We have two options:
a) We use a phylo2L function, which fortunately has been already written by Liang. In case I will add additional tests, of course;
b) Replace the function TESS::tess.sim.taxa.age in raz_create_bd_tree with dd_sim and add an additional layer that forces to re-simulate until the expected number of tips is matched.
@richelbilderbeek what do you think?

**Comment by richelbilderbeek** [comment]
Option A! I'd love to add a `phylo2L` function!

**Comment by richelbilderbeek** [comment]
@Giappo: undo: AFAICS, we do not need an L-table for a BD tree. I will update the Issue's title and text.

**Comment by Giappo** [comment]
too late :D

**Comment by richelbilderbeek** [comment]
All tests pass == happy Richel. God job  :+1:
