### ISSUE TITLE
Remove all raz_ prefixes

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#108]
Currently, all functions are prefixed with `raz_`.

I suggest to remove all `raz_` prefixes  (see reason below).

To prevent merge conflicts, this will be done after all work is merged to `develop`.

@Giappo:

 * [x] I agree
 * [x] I merged my work with `develop`

## Reason

Prefixing functions may look smart, but I think it is not. 
A smart reason to prefix function names are when function names can clash with other packages,
which applies mostly to general-use packages.

Our package does not have function names that can clash with other packages, 
nor is it intended for general use. That means we unnecessarily hurt readability.

**Comment by Giappo** [comment]
I totally agree. Proceed with that!

**Comment by Giappo** [comment]
As a side note:
I prefer to naming keeping only the words that actually provide information (not like "raz_", for example) about what functions do and I prefer to abbreviate the least possible.
Feel free to change other names accordingly to these principles.
