### ISSUE TITLE
Fix non-windows tests

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#119]
"test-create_mbd_marg_lik_file", "test-create_bd_marg_lik_file", "test-est_marg_lik" fail. They cannot be fixed on windows computers.

**Comment by richelbilderbeek** [comment]
Hmmm, it was easy to fix, as I've fixed those same bugs the day before. Must have been some merge conflicts that went sideways.

**Comment by richelbilderbeek** [comment]
Fixed 'em!
