### ISSUE TITLE
Create same parameters as in the article

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#127]
Currently, we just pick some values. It's time to pick values we'll use in the article. Do so at the section where we create the parameters.

Also, creating that parameter set needs some work, due to a new interface. Start here:

```
test_that("use, full", {

  skip("Issue 127, #127")

  # ...
})
```

**Comment by richelbilderbeek** [comment]
Derivation of the parameters:

[parameters.pdf](https://github.com/richelbilderbeek/razzo/files/2649143/parameters.pdf)

**Comment by richelbilderbeek** [comment]
This one is ready to be read by Giappo:

[parameters.pdf](https://github.com/richelbilderbeek/razzo/files/2651998/parameters.pdf)

**Comment by richelbilderbeek** [comment]
Depends on [https://github.com/richelbilderbeek/pirouette/issues/64](https://github.com/richelbilderbeek/pirouette/issues/64)

**Comment by Giappo** [comment]
To define the parameters for the experiment go in "create_parameters_files" and add the right parameters combination for the experiment type "full".
To do so you need to create the right "mbd_params" using the function "create_mbd_params_interval"
