### ISSUE TITLE
Add recorded number of nu events to mbd_sim

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#139]

**Comment by Giappo** [comment]
@richelbilderbeek: please take a look at the presentation we discussed with Rampal. 

If this Issue is valid, reassign me. Else close this Issue :+1:

**Comment by richelbilderbeek** [comment]
[Here is the presentation](https://github.com/richelbilderbeek/razzo/blob/richel/doc/choices.pdf). We chose to use `nu` instead of `n_nu_events`. Closing this Issue.
