### ISSUE TITLE
1. Use parameter 'n_events' instead of 'nu'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#146]
We already agreed on this: instead of using different values of nu, we use a number of co-occurring speciation events, with values like, for example, 0, 1, 2, 4, 8.

The `nu` parameter can be removed from the parameters and be replaced by this new parameter. If it is named `n_events`, `n_spec_events`, `n_co_spec_events` (my personal favorite) or `n_trig_events`, I can live with any of these names.

**Comment by richelbilderbeek** [comment]
After #151, put `n_events` in the `misc_params` section of a `razzo_params` structure.

After this `run_razzo` has to call `becosys::bco_mbd_sim` differently, or a different function instead.

**Comment by richelbilderbeek** [comment]
I think Giovanni will like this one :+1:

**Comment by Giappo** [comment]
Please check presentation first. 

If this Issue is valid, please assign me. Else close.

**Comment by richelbilderbeek** [comment]
[Here is the presentation](https://github.com/richelbilderbeek/razzo/blob/richel/doc/choices.pdf). We chose to use `nu` instead of `n_nu_events`. Closing this Issue.
