### ISSUE TITLE
Add 'misc' to razzo_params

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#151]
The `razzo_params` structure needs an additional member, called `misc_params`

Add

 * `create_misc_params`
 * `check_misc_params`
 * `create_razzo_params` must have an extra argument: `misc_params`
 * `check_razzo_params` must check the `misc_params` argument
 
A `misc_params` must have:

 * `tree_filename`: to store the original given tree
 * `mbd_sim_rng_seed`: RNG seed for when an MBD tree is simulated

**Comment by richelbilderbeek** [comment]
I think Giovanni would like this one :+1:

**Comment by Giappo** [comment]
@richelbilderbeek do we actually need the tree_filename?
Can't we just call it "mbd.tree" and put it in the right folder? (lambda-mu-nu-q/seed/)

**Comment by richelbilderbeek** [comment]
Yes, we need that `tree_filename`. I was also surprised to find out, do not remember the context from the top of my head, but yes, I remember I really needed that in `raket`.

**Comment by Giappo** [comment]
I don't really understand why, but I trust you.
I will make it in such a way it'll be always "mbd.tree" in "create_parameters_file".
I hope it's fine for you.

**Comment by richelbilderbeek** [comment]
Well done, thanks!
