### ISSUE TITLE
Define properly how to make becosys and razzo interface with each other

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#159]
"create_razzo_params" is a function that needs the following arguments:
- mbd_params
- twinning_params
- alignment_params
- model_select_params
- inference_params
- misc_params
mbd_params should be created by becosys::create_mbd_params
This function should provide the following arguments (i believe):
- lambda
- mu
- nu
- q
- cond
- crown_age
- seed
So we want all of them to be parsed into "mbd_params" argument of "create_razzo_params". Is it correct?

**Comment by Giappo** [comment]
In case, we have to change the rest of becosys accordingly (e.g. arguments of mbd_sim).
An alternative could be to completely rule out becosys and write the functions we need directly into razzo, which would probably make everything much faster and simpler.

**Comment by richelbilderbeek** [comment]
Go ahead and remove that becosys dependency (#160) :+1: 

I've [update the doc (on develop)](https://github.com/richelbilderbeek/razzo/tree/develop/doc) and put a recent pic here below. I hope that helps :rocket: 

![overview](https://user-images.githubusercontent.com/2098230/51963206-20abc100-2463-11e9-8cf2-a4dd663d63bf.png)

**Comment by richelbilderbeek** [comment]
Hmmm, duplication of parameters is always (I can think of no exceptions) a bad idea.

OTOH if you check the duplicated info being equal and it helps you go forward, go ahead :+1:
