### ISSUE TITLE
Check if run_razzo produces the correct output

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#165]
run_razzo (or run_razzo_from_file) seems to work.
The problem though is that even though we know that an output is produced, we are not sure if it is the correct one.
Please check if it is correct.
This issue is connected to #163 as we want to control where the output is created.
Issues #138 and #141  depend in this as we need the output to be correct (and I need to understand exactly how it's done) to plug the results into figure functions.

**Comment by richelbilderbeek** [comment]
I take the liberty of closing this Issue. AFAICS, all files are created in all locations needed. We need to check indeed, but I feel most is done already :rainbow:
