### ISSUE TITLE
Start using new pirouette interface

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#166]
I think I've heavily improved the pirouette interface, as can be seen in this vignette:
[https://github.com/richelbilderbeek/pirouette/blob/richel/vignettes/setup.Rmd](https://github.com/richelbilderbeek/pirouette/blob/richel/vignettes/setup.Rmd)

It is not done yet, but you could already help in e.g. razzo:

Every time we now use 'model_select_params' and 'inference_params', do:

## 1)

```{r}
inference_params$rng_seed <- 314159265 # secret trick to activate new interface
```

## 2)

```{r}
experiments <- ... # create those experiments in the 'create_experiment' format
```

## 3)

call pir_run with:

```{r}
pir_run(
  # ...
  experiments = experiments
)
```

Keep the old usage of 'model_select_params' and 'inference_params' intact, to keep the tests passing.

Once the new interface is finished, the 'model_select_params' and 'inference_params' can be deleted, and I think you'd be happy to help there as well.

If questions, let me know :+1:

**Comment by Giappo** [comment]
Now it's possible to call run_razzo and run_razzo_from_file with the additional argument "experiments"

**Comment by richelbilderbeek** [comment]
My turn :+1:

With `pir_params` being there, this will be easypeasy :four_leaf_clover:

**Comment by richelbilderbeek** [comment]
Works!
