### ISSUE TITLE
"beast2_working_dir" should be part of create_test_razzo_params

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#185]
When running many tests we call the following:

```
parameters <- open_parameters_file(file.path(paths[p], "parameters.RDa")) # nolint internal function
```

When this happens a check is automatically performed on the parameters:

```
check_razzo_params(parameters)
```

which includes

```
pirouette::check_pir_params(razzo_params$pir_params)
```

Which fails, with error:

```
 Error in value[[3L]](cond) : 
  'experiments' must be one experiment or a list of one or more experiments.
Tip: use 'create_experiments'
Error message: 'experiments[[1]] invalid.
Tip: use 'create_experiment' for each list element.
Error: 'beast2_options' must be valid BEAST2 options.
Tip: use 'beastier::create_beast2_options'.
Error: 'beast2_working_dir' must be an element of an 'beast2_options'. Tip: use 'create_beast2_options'
Value: /home/richel/GitHubs/razzo/inst/extdata/razzo_project/data/0.2-0.15-1-0.1/1/mbd_gen.xml/home/richel/GitHubs/razzo/inst/extdata/razzo_project/data/0.2-0.15-1-0.1/1/mbd_gen.log/home/richel/GitHubs/razzo/inst/extdata/razzo_project/data/0.2-0.15-1-0.1/1/mbd_gen.trees/home/richel/GitHubs/razzo/inst/extdata/razzo_project/data/0.2-0.15-1-0.1/1/mbd_gen.xml.state1NAFALSETRUE/home/richel/.local/share/beast/lib/beast.jarFALSE
Value: list(site_model = list(name = "JC69", id = NA, gamma_site_model = list(gamma_cat_count = "0", gamma_shape = "1.0", prop_invariant = "0.0", gamma_shape_prior 

I think this can be broken down in the following errors:
1) "experiments" are not bundled correctly;
2) "beast2_working_dir" is not provided;
3) more?

What is wrong? The test or the data we load?
```

**Comment by Giappo** [comment]
@richelbilderbeek can you help me understand how to proceed?

**Comment by richelbilderbeek** [comment]
Usually this happens to me from:

```
# incorrect! 
experiments <- create_test_gen_experiment()
```

this is incorrect because `length(experiments)` must equal the number of experiments. Solution:

```
# Correct 
experiments <- list(create_test_gen_experiment())
```

I can read this in indeed the case from the error message:

```
Error message: 'experiments[[1]] invalid.
Tip: use 'create_experiment' for each list element.
```

Hope that helps, will be away from computer the rest of the day...

**Comment by richelbilderbeek** [comment]
Usually this happens to me from:

```
# incorrect! 
experiments <- create_test_gen_experiment()
```

this is incorrect because `length(experiments)` must equal the number of experiments. Solution:

```
# Correct 
experiments <- list(create_test_gen_experiment())
```

I can read this in indeed the case from the error message:

```
Error message: 'experiments[[1]] invalid.
Tip: use 'create_experiment' for each list element.
```

Hope that helps, will be away from computer the rest of the day...

**Comment by Giappo** [comment]
That is not the error. The problem, apparently, is in:

beastier::check_beast2_options(experiment$beast2_options)

Which leads to the error:

"Error: 'beast2_working_dir' must be an element of an 'beast2_options'. Tip: use 'create_beast2_options'"

The structure must be the following:
razzo_params$pir_params$experiments[[1]]$inference_model$beast2_options$beast2_working_dir

The problem is that it is impossible to actually build it, because "beautier::create_inference_model" does not actually include the possibility to include beast2_options. I attach here the help of the function to make it clear:
`create_inference_model(site_model = create_jc69_site_model(),
  clock_model = create_strict_clock_model(),
  tree_prior = create_yule_tree_prior(), mrca_prior = NA,
  mcmc = create_mcmc(), beauti_options = create_beauti_options(),
  tipdates_filename = NA)`

The solution I propose is therefore to fix it in beautier, in such a way "create_inference_model" can actually include "beast2_options" in its output.

**Comment by Giappo** [comment]
Ok, apparently "create_test_razzo_params" has no use. The function to use is instead "create_parameters_files".
I changed it, then I run it and the parameters are now ok. The problem is that now in the folders there is nothing more than the (right) parameters.RDa, so everything else fails.
How can I recreate the other files?

**Comment by Giappo** [comment]
Depends on #187

**Comment by richelbilderbeek** [comment]
See #187 how to create the other files. You'll need Linux to do so, unless you'll add [this feature](https://github.com/ropensci/babette/issues/68)

**Comment by richelbilderbeek** [comment]
I am close to rounding this off ...

**Comment by richelbilderbeek** [comment]
Results have Peregrine friendly names :+1:
