### ISSUE TITLE
Leave only two functions to create parameters: one for test and one for experiment

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#186]
Now there are:
- create_razzo_params
- create_test_razzo_params
- create_parameters_files
- create_full_parameters_files
- create_test_parameters_files

All these functions create a lot of confusion.
I suggest to have one for test and one for experiment. At maximum we can add their counterparts to save into file (probably they should be named save, more than create) which just call the original create functions and save.

**Comment by richelbilderbeek** [comment]
> All these functions create a lot of confusion.

Hmmm, I think these functions do exactly as their name implies: they create a parameter set or they create files (including the folders needed). I dislike the name `create_full_parameters_files`, as it should have been something like `create_full_experiment_parameters_files`, as it creates those files for the full experiment in our paper. `create_test_parameters_files` is just a shorthand for `create_parameters_files(... = "test")`, as I expect that when I type `create_test_`, I get a list of test things to create.

I think using `save` is an interesting idea, but it would confuse *me*: if I want to create something, I type `create_` to get a list of functions that I can use. I'd be willing to change the name, but I fail to see the worth of it. OTOH, if you think it is worth it, go ahead and change, but please do so in `razzo_project` and run it on Peregrine to get the full 'Was it worth it?' experience. I feel I'd prefer you to work on the manuscript, for you wellbeing as well :+1: 

> I suggest to have one for test and one for experiment

You mean, rename `create_full_parameters_files` to `create_full_experiment_parameters_files`? Go ahead!

>  At maximum we can add their counterparts to save into file (probably they should be named save, more than create) which just call the original create functions and save.

Aha, I think I see what you mean:

Current name|Giappo's ideal name
---|---
`create_razzo_params`|`create_params`
`create_test_razzo_params`|`create_test_params`

I'd enjoy these names, but our users would not like it. `create_params` feels too common of a function name to me.

Current name|Giappo's ideal name
---|---
`create_parameters_files`|`save_params`
`create_full_parameters_files`|`save_experiment_params`
`create_test_parameters_files`|`save_test_params`

When I now take a look at this table, I only increase the confidence in the current naming scheme: `save_params` implies:

```r
save_params <- function(params) {
  # Save params to file
}
```

`save_experiment_params` implies:

```r
#' @param paramses list of params
save_experiment_params <- function(paramses) {
  # Save params sets to files
}
```
