### ISSUE TITLE
Create 'raz_create_params'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#19]
The function `raz_create_params` creates parameters that are named and checked. Although a trivial function, it assures that we use correct parameter values.

Marked with `TODO, Issue #19`.

 * `tests/testthat/test-raz_create_params.R` tests it, but these tests are skipped
 * `raz_create_params` should call it (instead of using `c` to combine all values

**Comment by Giappo** [comment]
Don't we have already the function "raz_open_parameters_file" that does what you want?

**Comment by richelbilderbeek** [comment]
> Tbh, It feels a bit like overkill
I understand that feeling. We both feel one should always check inputs of exported functions, which is the recommended attitude. 

But the additional idea is to have each function has one well-defined purpose:

 * `create_params`: creates a checked set of parameters
 * `create_parameter_files`: creates and saves multiple of those

If that does not convince you, that is fine, and I will happy write that function one Monday...

Keep up the good work :+1:

**Comment by Giappo** [comment]
Ok Richel, I started working a bit on that. I want to know what you think about it.
I am also wondering: do we really need to use 'id'? I don't think it is important, isn't it?

**Comment by richelbilderbeek** [comment]
Yup, I've seen the push! I'm happy to see some thorough testing!

I also now see what you meant with overkill, and in this context, I do agree it is: a lambda is just a double (in `beautier`, these **are** more complex things and there an `id` makes sense. In our case, I feel we don't need it). Well, my bad, but the code certainly is useful, and I will definitely call these functions when I can.

Well done :+1:
