### ISSUE TITLE
Create Fig 1

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#194]
It has to show delta_twin / delta_true as a function of nu and q, as in sls manuscript, figure 2 (heatmap)

**Comment by richelbilderbeek** [comment]
From the parameter combinations in the manuscript, I deduce it will look something like this:

![fig_1](https://user-images.githubusercontent.com/2098230/59758547-71934900-928e-11e9-9480-6e0892c447bd.png)

How to calculate the Z value or color in the figure is another Issue :grinning:

**Comment by richelbilderbeek** [comment]
I would enjoy some annotation. Currently, there is ...

![20190620_figure_1](https://user-images.githubusercontent.com/2098230/59847388-a07aef00-9362-11e9-9067-17e51d2f5ac3.png)

.. where something like this would publishable:

![20190620_figure_1_annotated](https://user-images.githubusercontent.com/2098230/59847390-a1138580-9362-11e9-9b18-dd0440757ba0.png)

**Comment by richelbilderbeek** [comment]
@Giappo: I see there are no enabled tests to check if the function works correctly, for example:

```r
context("test-create_fig_1")

test_that("use", {
  skip("WIP")
  # Should return plot
  plot <- create_fig_1(
    project_folder_name = get_razzo_path("razzo_project")
  )
  expect_true(
    all(class(plot) == c("gg", "ggplot"))
  )
})
```

Running that test manually results in an error.

It would be a good idea to enable these tests :grin: :+1:
