### ISSUE TITLE
Create nice dna alignment figures on Peregrine

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#198]
When one creates e.g an alignment, like e.g. this ...

```r
dna_alignment <- phangorn::[create...]
png("myfile.png")
image(dna_alignment)
dev.off()
```

it always looks crappy. Find out how to make a pretty picture on Peregrine.

**Comment by Giappo** [comment]
The code you are looking for is this:
`png("myfile.png", width = 800, height = 600, res = 144); ape::image.DNAbin(x = dna_alignment); dev.off()`
If I search in the package the only use of the function "image" is in "razzo_pipeline.Rmd". Is it the only place where to put it or there is more?

**Comment by richelbilderbeek** [comment]
Blimey, you may have found it! Will test when I need it :+1:

**Comment by Giappo** [comment]
:rainbow:

**Comment by richelbilderbeek** [comment]
Works!

<img width="400" alt="alignment" src="https://user-images.githubusercontent.com/2098230/61209692-b7f78e80-a6fa-11e9-9f30-ec339ce69e3e.png">
