### ISSUE TITLE
Make runs independent

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#201]
Currently, multiple runs share the same seed:

```r
mbd_paramses <- razzo::create_paramses_mbd(
  lambda = 0.2,
  mu = c(0, 0.15),
  nu = c(1.0, 1.5, 2.0, 2.5),
  q = c(0.1, 0.15, 0.2),
  seed = seq(from = 1, to = n_replicates, by = 1),
  crown_age = 6.0,
  cond = 1
)
```

Sharing a same seed definitely has a place in a simulatio study (e.g. to 
gain insight in which part contributes to a certain effect).

In our context, however, when exploring the parameter statespace, I feel 
strongly that our runs need to be completelt indepedent.

I suggest that either

 * 1) RNG seeds start from 1, increment by 1 per parameter set, thus
   ensuring every run is independent.
 * 2) RNG seeds are pick randomly per parameter setting

I'd prefer option 1.

**Comment by Giappo** [comment]
Usually I do the same with my likelihood models. I am wondering if this can lead to an actual problem or not. I'll ask Rampal, to be sure.
Anyways, I tried to implement ii. I failed.
I implemented i.
Seems to work. Waiting for Travis to give me the OK.

**Comment by richelbilderbeek** [comment]
Cool, I enjoy the option i best! :+1:

**Comment by Giappo** [comment]
The code to do that is on my branch and it passes tests.
I close this.
