### ISSUE TITLE
Annotate figure 1 better

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#204]
I would enjoy some annotation. Currently, there is ...

![20190620_figure_1](https://user-images.githubusercontent.com/2098230/59847388-a07aef00-9362-11e9-9067-17e51d2f5ac3.png)

.. where something like this would publishable:

![20190620_figure_1_annotated](https://user-images.githubusercontent.com/2098230/59847390-a1138580-9362-11e9-9b18-dd0440757ba0.png)

**Comment by richelbilderbeek** [comment]
To have data to work on, one could use the results as in `inst/extdata/razzo_project/results` or use the full results as in the zip in #203

**Comment by Giappo** [comment]
create_fig_1 does it now
