### ISSUE TITLE
ESSes are obtained incorrectly

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#206]
These are outputs of earlier runs:

 * [20190620_2](http://richelbilderbeek.nl/razzo_project_20190620_2.zip)
   1 replicates, crown age = 6, MCMC = 3k
 * [20190620_3](http://richelbilderbeek.nl/razzo_project_20190620_3.zip)
   2 replicates, crown age = 6, MCMC = 3k
 * [20190621](http://richelbilderbeek.nl/razzo_project_20190621.zip): 
   2 replicates, crown age = 6, MCMC = 100k

in `results/esses.csv` I do not see the Effective Sample Sizes at all.

I predict there are some tests turned off :rainbow:

**Comment by richelbilderbeek** [comment]
Example idea of expected output:

Run|posterior|likelihood
---|---|---
1     |80          | 79

**Comment by Giappo** [comment]
Hi @richelbilderbeek ,

I am not sure I am following you in this. Can you help me understand better what is the problem?
I opened the file esses.csv that you referred to. I find a dataframe with a bunch of stuff. I suppose you are referring to the columns "posterior" and "ess_likelihoood". 
Why do you want them to be positive?
How is this related to the issue?
What tests are you talking about? Tests for the function "collect_esses"?

**Comment by richelbilderbeek** [comment]
I was aware of me being not perfectly clear. Sorry for the noise!

Effective Samples Sizes should be positive, because it represents a number of effective/independent samples.

A [reprex](https://stackoverflow.com/help/minimal-reproducible-example):

```
library(babette)
traces <- tracerer::parse_beast_log(
  babette::get_babette_path("anthus_aco_sub.posterior.log")
)
esses <- tracerer::calc_esses(traces, sample_interval = 1000)
```

results in

```
  posterior likelihood prior treeLikelihood TreeHeight YuleModel birthRate
1         4          3     6              3          6         6         6
```

This denotes that the posterior has been samples effectively 4 times, where the birthRate has been sampled effectively 6 time. The difference has to do with the autocorrelation/dependence of samples.

In our code, a [reprex](https://stackoverflow.com/help/minimal-reproducible-example) would be:

```
library(razzo)
df <- collect_esses(
  project_folder_name = get_razzo_path("razzo_project")
)
```

where `df` is:

```
   lambda   mu nu   q seed crown_age cond Sample            posterior      ess_likelihood                prior
1     0.2 0.15  1 0.1    1        15    1      0 -8.625475552291847E9  -1799.532030120938 -8.625473752759817E9
2     0.2 0.15  1 0.1    1        15    1   1000    -67773.6556940672   -1093.48048765568   -66680.17520641153
3     0.2 0.15  1 0.1    1        15    1   2000   -66146.81886568636  -923.7923395713539  -65223.026526115005
```

Errors are:

 * The samples taken at 0, 1000 and 2000 timesteps are still present, where an ESS is calculated over all samples
 *  `ess_likelihood` is present, but a number of samples can never be negative
 * The sampled values of `posterior` and `prior` are irrelevant 

It would be correct if it would look more like:

```
   lambda   mu nu   q seed crown_age cond        ess_likelihood
1     0.2 0.15  1 0.1    1        15    1                   123
```

I hope that helps!

**Comment by Giappo** [comment]
Hi @richelbilderbeek , thank you for the explanations. It is clearer now. I have reworked the function using tracerer::calc_esses. I pushed a version that should do what you asked. Please give it a look and tell me if it does what you want.

**Comment by richelbilderbeek** [comment]
Cool, will check in a couple of hours :+1:

**Comment by richelbilderbeek** [comment]
OK, running

```
df <- collect_esses(
  project_folder_name = get_razzo_path("razzo_project")
)
```

results in the folliowing table:
 
| lambda|   mu| nu|   q| seed| crown_age| cond| ess_likelihood|site_model |clock_model |tree_prior  |best_or_gen |tree |
|------:|----:|--:|---:|----:|---------:|----:|--------------:|:----------|:-----------|:-----------|:-----------|:----|
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |twin |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |twin |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |twin |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |twin |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |true |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |true |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |true |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |yule        |best        |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |yule        |best        |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |yule        |best        |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |yule        |best        |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|GTR        |strict      |birth_death |best        |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|GTR        |strict      |birth_death |best        |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|GTR        |strict      |birth_death |best        |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|GTR        |strict      |birth_death |best        |true |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              3|JC69       |strict      |birth_death |gen         |true |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              3|JC69       |strict      |birth_death |gen         |true |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              3|JC69       |strict      |birth_death |gen         |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |true |

There are some duplicates, but it's a great start! 

I've fixed it, it now results in:

| lambda|   mu| nu|   q| seed| crown_age| cond| ess_likelihood|site_model |clock_model |tree_prior  |best_or_gen |tree |
|------:|----:|--:|---:|----:|---------:|----:|--------------:|:----------|:-----------|:-----------|:-----------|:----|
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              3|JC69       |strict      |birth_death |gen         |true |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |true |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|              4|JC69       |strict      |yule        |best        |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|GTR        |strict      |birth_death |best        |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |birth_death |gen         |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|              4|JC69       |strict      |yule        |best        |twin |

Well done team razzo!
