### ISSUE TITLE
How big are our phylogenies?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#210]
I have a good idea how long [our last successful run](http://richelbilderbeek.nl/razzo_project_20190621.zip) takes. But I do not know the number of taxa our phylogenies have.

Create a function `collect_n_taxa` that follows the same structure as `collect_esses`.

Here are the tests, in `test-collect_n_taxa.R`: 
```r
test_that("use", {

  skip("Issue #210")
  if (1 == 2) {
    # Run the experiment if you can and need to
    for (file in list.files(get_razzo_path("razzo_project"), recursive = TRUE, pattern = "parameters\\.RDa")) {
      run_razzo(open_parameters_file(file))
    }
  }
  df <- collect_n_taxa(
    project_folder_name = get_razzo_path("razzo_project")
  )

  # Experimental parameters that vary
  expect_true("lambda" %in% names(df))
  expect_true("mu" %in% names(df))
  expect_true("nu" %in% names(df))
  expect_true("q" %in% names(df))
  expect_true("seed" %in% names(df))
  expect_true("site_model" %in% names(df))
  expect_true("clock_model" %in% names(df))
  expect_true("tree" %in% names(df))
  # The number of taxa
  expect_true("n_taxa" %in% names(df))

  # Data must be tidy
  expect_true(is.factor(df$clock_model))
  expect_true(is.factor(df$site_model))

  # Rows must be unique
  expect_equal(nrow(unique(df)), nrow(df))
})
```

**Comment by richelbilderbeek** [comment]
Tests are on `develop` now.

**Comment by Giappo** [comment]
What trees are we talking about? These are the options:
1) 'true' original tree;
2) 'twin' original tree;
3) 'true' gen posterior trees;
4) 'twin' gen posterior trees;
5) 'true' best posterior trees;
6) 'twin' best posterior trees;
I suppose you want 1) and 2). Am I correct?

**Comment by Giappo** [comment]
I implemented 1) and 2). Probably this issue can be closed.

**Comment by richelbilderbeek** [comment]
As far as I thought I knew, these should have all been the same:

![ms](https://user-images.githubusercontent.com/2098230/61212178-c301ed00-a701-11e9-877a-41ef72f357df.png)

I'll see what's wrong...

**Comment by richelbilderbeek** [comment]
[Here](https://github.com/richelbilderbeek/pirouette/blob/richel/tests/testthat/test-create_twin_tree.R#L59) I see that we test for the number of taxa of true and twin tree to be the same. We do that in more places, so what causes the twin tree to have a different number of taxa?

**Comment by richelbilderbeek** [comment]
Indeed the number of taxa of true and twin tree is the same:

![indeed_the_same](https://user-images.githubusercontent.com/2098230/61214344-fc3d5b80-a707-11e9-91d1-750e8ef96061.png)

Let's group the number of taxa for twin and true tree together...

**Comment by richelbilderbeek** [comment]
Hmmm, there is something fishy going on here:

```r
# test-collect_n_taxa.R

test_that("use", {

  if (1 == 2) {
    # Run the experiment if you can and need to
    for (file in list.files(get_razzo_path("razzo_project"), recursive = TRUE, pattern = "parameters\\.RDa")) {
      run_razzo(open_parameters_file(file))
    }
  }
  df <- collect_n_taxa(
    project_folder_name = get_razzo_path("razzo_project")
  )
  knitr::kable(df, format = "markdown")
  # ...
}
```

results in:




| lambda|   mu| nu|   q| seed| crown_age| cond| n_taxa|site_model |clock_model |tree |
|------:|----:|--:|---:|----:|---------:|----:|------:|:----------|:-----------|:----|
|    0.2| 0.15|  1| 0.1|    1|        15|    1|     45|JC69       |strict      |true |
|    0.2| 0.15|  1| 0.1|    1|        15|    1|     76|JC69       |strict      |twin |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|      6|JC69       |strict      |true |
|    0.2| 0.15|  1| 0.1|    2|        15|    1|      6|JC69       |strict      |twin |

I will need to regen the data I guess ...

**Comment by Giappo** [comment]
Well spotted.
I added a new test to check that. I will look in the code soon.

**Comment by richelbilderbeek** [comment]
Already added a test to pirouette :+1:

**Comment by Giappo** [comment]
I checked collect_n_taxa and it seems to work fine. Probably the error is in the data (somehow). Do you want me to remove the test in razzo or (as I prefer) we leave it as a consistency check on the data?

**Comment by richelbilderbeek** [comment]
> Probably the error is in the data (somehow)

It is. 

After `razzo_project/scripts/regen_data.sh`:

```
p230198@peregrine:razzo_project cat results/n_taxa.csv 
"","lambda","mu","nu","q","crown_age","cond","seed","n_taxa","site_model","clock_model","tree"
"1",0.2,0.15,1,0.1,6,1,1,6,"JC69","strict","true"
"2",0.2,0.15,1,0.1,6,1,1,6,"JC69","strict","twin"
"3",0.2,0.15,1,0.1,6,1,2,4,"JC69","strict","true"
"4",0.2,0.15,1,0.1,6,1,2,4,"JC69","strict","twin"
```

Wll send fresh data to razzo's inst/exdata folder now.

> Do you want me to remove the test in razzo or (as I prefer) we leave it as a consistency check on the data?

As I too prefer: keep the test in. Will update data now and fix test in `test-collect_n_taxa.R`

**Comment by richelbilderbeek** [comment]
Fresh data:

[razzo_project_regen_data_20190717.zip](https://github.com/richelbilderbeek/razzo/files/3392480/razzo_project_regen_data_20190717.zip)

**Comment by richelbilderbeek** [comment]
Lookin' good:

```r
# test-collect_n_taxa.R

test_that("use", {

  if (1 == 2) {
    # Run the experiment if you can and need to
    for (file in list.files(get_razzo_path("razzo_project"), recursive = TRUE, pattern = "parameters\\.RDa")) {
      run_razzo(open_parameters_file(file))
    }
  }
  df <- collect_n_taxa(
    project_folder_name = get_razzo_path("razzo_project")
  )
  knitr::kable(df)
  # ...
}
```

| lambda|   mu| nu|   q| crown_age| cond| seed| n_taxa|site_model |clock_model |tree |
|------:|----:|--:|---:|---------:|----:|----:|------:|:----------|:-----------|:----|
|    0.2| 0.15|  1| 0.1|         6|    1|    1|      6|JC69       |strict      |true |
|    0.2| 0.15|  1| 0.1|         6|    1|    1|      6|JC69       |strict      |twin |
|    0.2| 0.15|  1| 0.1|         6|    1|    2|      4|JC69       |strict      |true |
|    0.2| 0.15|  1| 0.1|         6|    1|    2|      4|JC69       |strict      |twin |

Will fix tests now.

**Comment by Giappo** [comment]
Ok, merging with develop as soon as ci check ends.
BTW, how is it possible that twin trees with different number of tips are generated? Do you think there might be a bug in pirouette? I thought there was already a test to check it...

**Comment by richelbilderbeek** [comment]
@Giappo: you want to do the finishing blow to this Issue? 

To do so, make the tests under `skip("#210")` in `test-collect_n_taxa.R`:

```r
test_that("use", {

  if (1 == 2) {
    # Run the experiment if you can and need to
    for (file in list.files(get_razzo_path("razzo_project"), recursive = TRUE, pattern = "parameters\\.RDa")) {
      run_razzo(open_parameters_file(file))
    }
  }
  df <- collect_n_taxa(
    project_folder_name = get_razzo_path("razzo_project")
  )

  # Experimental parameters that vary
  expect_true("lambda" %in% names(df))
  expect_true("mu" %in% names(df))
  expect_true("nu" %in% names(df))
  expect_true("q" %in% names(df))
  expect_true("seed" %in% names(df))
  expect_true("site_model" %in% names(df))
  expect_true("clock_model" %in% names(df))
  # The number of taxa
  expect_true("n_taxa" %in% names(df))

  # Data must be tidy
  expect_true(is.factor(df$clock_model))
  expect_true(is.factor(df$site_model))

  # Rows must be unique
  expect_equal(nrow(unique(df)), nrow(df))


  skip("#210")
  # As true and twin trees have the same number of taxa, no need
  # to have a 'tree' (with values 'true' or 'twin') column
  expect_false("tree" %in% names(df))

  # As all trees (true, twin, posterior) have an equal amount of tips
  n_rows_expected <- length(
    list.files(
      get_razzo_path("razzo_project"),
      recursive = TRUE,
      pattern = "parameters\\.RDa"
    )
  )
  expect_equal(nrow(df), n_rows_expected)
})
```
It's on the `richel` branch.

You wanna?

> BTW, how is it possible that twin trees with different number of tips are generated?

No idea.

>  Do you think there might be a bug in pirouette?

No, `pirouette` already did fine.

>  I thought there was already a test to check it...

In the test suite, yes. Now the output (i.e. the twin tree) of `create_twin_tree` is *also* tested to have the same number of tips as the original tree. Superfluous yet satisfactory :+1:

**Comment by Giappo** [comment]
Ofc I can do that. How do we test the regenerated data tho?

**Comment by richelbilderbeek** [comment]
The regenerated data is already tested by many of our tests, so little need to worry about that. It's just this tiny little Issue now that is buggering us. Enjoy smashing it!
