### ISSUE TITLE
Bug in collect_esses

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#220]
There is a bug in `collect_esses` as it does not calculate the ESSes as specified by the user.

To calculate an ESS, one needs:

 * a trace (i.e. parameter estimates)
 * a burn-in fraction (the initial fraction of values that is to be discarded)(needed as an MCMC needs to reach a representative sampling state)
 * a sampling interval

Currently, a burn-in of zero % is used and a sampling interval of 1e6.

Below (and in the code) I show first where to obtain the burn-in fraction and sampling interval, in an `1 == 2` if statement. Below that I give an example how to correctly call `tracerer::calc_esses`.

Note that sampling interval can differ per parameter file.

```r
collect_esses <- function(
  project_folder_name = get_razzo_path("razzo_project")
) {
  # ...
  for (p in seq_along(paths)) {
    # ...
    # Need this: Issue #220
    if (1 == 2) {
      burn_in_fraction <- parameters$pir_params$error_measure_params$burn_in_fraction # nolint indeed unused yet
      sample_interval <- parameters$pir_params$experiments[[1]]$inference_model$mcmc$store_every # nolint indeed unused yet
    }
    # ...
  }
  # ...
  for (i in seq_along(all_esses$settings)) {
    # ...
    if (1 == 1) {
      ess_likelihood[i] <- unlist(tracerer::calc_esses(traces, sample_interval = 1e6))["likelihood"]
    } else {
      # Need this: Issue #220
      # Remove burn-ins, burn_in_fraction obtained earlier
      clean_traces <- tracerer::remove_burn_ins(traces, burn_in_fraction = burn_in_fraction)
      # Calculate the correct ESSes, sample_interval obtained earlier
      ess_likelihood[i] <- unlist(
        tracerer::calc_esses(clean_traces, sample_interval = sample_interval)
      )["likelihood"]
    }
    # ...
  )
  # ...
}
```

With the current tests, it cannot be checked if this is done correctly. I will work on that.

**Comment by Giappo** [comment]
@richelbilderbeek it seems that what you wrote does exactly what you wanted. I cannot do more than this, apparently :D

**Comment by Giappo** [comment]
I feel like this :man_in_tuxedo: 
[https://i.kym-cdn.com/photos/images/original/001/240/075/90f.png](url)

**Comment by richelbilderbeek** [comment]
Hmm, let's fix this misunderstanding:

The code I showed had two if statements, one with `1 == 1` and the other with `1 == 2`. These were supposed to be helpful hints. Just removing the ifs would be incorrect.

@Giappo: perhaps phrasing the problem in a picture helps:

![issue_220](https://user-images.githubusercontent.com/2098230/61302645-73492180-a7e6-11e9-8039-ab34d207bec8.png)

**Comment by Giappo** [comment]
It looked suspiciously simple :D
Thanks for the explanation, it was very clear :rainbow:

**Comment by richelbilderbeek** [comment]
From 20190621 run, before:

[esses_before.zip](https://github.com/richelbilderbeek/razzo/files/3397858/esses_before.zip)

**Comment by richelbilderbeek** [comment]
From 20190621 run, after:

[esses_after.zip](https://github.com/richelbilderbeek/razzo/files/3398071/esses_after.zip)

On screen:

![fixed](https://user-images.githubusercontent.com/2098230/61311309-67655b80-a7f6-11e9-937d-43cf4c6b9ac6.png)
