### ISSUE TITLE
'collect_esses' slow on 96 files

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#228]
`collect_esses` does not scale well with bigger input. For testing input (approx 4 files) it works fast enough. For razzo run without replicates (approx 96 unique parameter combination) it takes too long.

Some informal profiling showed that `rbind` was the culprit, of which we knows scales exponentially with input size.

The script in [scripts/issue_228](https://github.com/richelbilderbeek/razzo/blob/richel/scripts/issue_228.R) reproduces this problem. I copy-pasted it here as well:

```r
zip_filename <- file.path(tempdir(), "razzo_project.zip")
curl::curl_download(
  url = "http://richelbilderbeek.nl/razzo_project_20190801.zip",
  destfile = zip_filename,
  quiet = FALSE # This download will take some time
)

razzo_project_folder <- file.path(dirname(zip_filename), "razzo_project")
dir.create(razzo_project_folder, recursive = TRUE)

utils::unzip(zipfile = zip_filename, exdir = razzo_project_folder)

# This takes ages, Issue #228, Issue 228
df <- collect_esses(
  project_folder_name = razzo_project_folder
)
```

**Comment by richelbilderbeek** [comment]
@Giappo: would you be up to improve upon your work?

**Comment by Giappo** [comment]
Thx, scripts/issue_228 is pure gold
