### ISSUE TITLE
What causes ESSes to be low?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#230]
When analyzing the latest run, I found out that the Effective Sample Sizes are abominably low, where they should be (mostly) above 200, as seen in `results/esses.csv`:
 
![crappy_esses](https://user-images.githubusercontent.com/2098230/62700762-025ee900-b9e3-11e9-89d5-5fbefd018011.png)

Find out what could be the case. 

There is a convenient script [here](https://github.com/richelbilderbeek/razzo/blob/richel/scripts/issue_230.R).

If there is a pattern, we can correct for this, by making the MCMC chain longer for the cases that need it.

Some informal observations:

 * ESSes are lower for the generative model 
 * A low ESS for the true tree also results in a low ESS for the twin tree

**Comment by Giappo** [comment]
Can it be due to trees that are extremely small?
I think we have a way to access tree information, right?

**Comment by richelbilderbeek** [comment]
> Can it be due to trees that are extremely small?

In theory, yes, but that would be unexpected: it is easier to explore a wider range of parameter space in small trees. Due to this, a likelier first expectation would be to assume the trees are big.

> I think we have a way to access tree information, right?

Yes, there is a `csv` with tree sizes in the results folder as well.

**Comment by Giappo** [comment]
What if we add the number of tips to the esses dataframe?

**Comment by richelbilderbeek** [comment]
Preferably not. In case you are unaware, [duck](https://duckduckgo.com/) for 'joining tables' to see how one usually combines tables (you will need an 'inner join').

But I do see the tables are set up sub-optimally: instead of using the folder of the experiment as a key, it uses the combination of all parameter settings. Joining tables on that will be awkward.

Would all tables have a unique key called 'folder', one can easily join tables. If you'd be up for that, you definitely have a 'go' in capitals from me!

**Comment by richelbilderbeek** [comment]
Actually, this:

> Would all tables have a unique key called 'folder', one can easily join tables. If you'd be up for that, you definitely have a 'go' in capitals from me!

would help me out for `raket` as well.

You agree it's a great idea, as (1) keys are unique, and (2) all data is unique (and we reach  [3NF](https://en.wikipedia.org/wiki/Database_normalization#Satisfying_3NF))?

**Comment by richelbilderbeek** [comment]
(note: using a folder name does have the problem that people store stuff on different locations. To fix that I'd suggest to use relative folder path compared to the `razzo_project`'s root. E.g. `/home/richel/razzo_project/data/1/2/3` would be `data/1/2/3`)

**Comment by Giappo** [comment]
Just to check if we are on the same page.
What you would like to have is that every "collect" function (such as collect_esses, collect_n_taxa and so on) return not lambda, mu, nu, q, crown_age, cond, seed but, at their place, a unique entry key in the data frame which is the path relative to the razzo_project's root.
Is it what you want?

**Comment by richelbilderbeek** [comment]
> Is it what you want?

Definitely!

**Comment by richelbilderbeek** [comment]
These are the four functions: to I suggest to add `folder` to:

 * [ ] collect_nltt_stats.R
 * [ ]  collect_esses.R
 * [ ]  collect_n_taxa.R
 * [ ] collect_marg_liks.R

I suggest to add (and volunteer to write):

 * [ ] collect_mbd_params.R

**Comment by Giappo** [comment]
I am on it

**Comment by richelbilderbeek** [comment]
Cool, good luck!

**Comment by Giappo** [comment]
I'd appreciate if you wrote the tests :taco:

**Comment by richelbilderbeek** [comment]
I'm on it :rocket:, will let you know when done (ETA +15 min)

**Comment by richelbilderbeek** [comment]
@Giappo: wrote the tests! Enjoy making these pass :+1:

**Comment by Giappo** [comment]
> Would all tables have a unique key called 'folder', one can easily join tables. If you'd be up for that, you definitely have a 'go' in capitals from me!

What's the easy way to join tables you were referring to?

**Comment by richelbilderbeek** [comment]
Here is a simple example:

```r
df_params <- data.frame(
  filename = c("a", "b", "c"),
  lambda = c(1, 2, 3),
  mu = c(0.1, 0.2, 0.3)
)

df_n_taxa <- data.frame(
  filename = c("a", "b", "c"),
  n_taxa = c(11, 22, 34)
)
  
df_merged <- merge(x = df_params, y = df_n_taxa, by = "filename")
```

Helpful?

**Comment by Giappo** [comment]
So, I looked a bit into the data.
I checked how the ess_likelihood behaves according to the different settings.
First, ess_likelihood vs numeric variables:

![ess_likelihood_vs_numeric_variables](https://user-images.githubusercontent.com/14541948/62943730-6dd9f980-bddb-11e9-9057-acf00a38c666.png)

Then, ess_likelihood vs non-numeric variables:

![ess_likelihood_vs_non_numeric_variables](https://user-images.githubusercontent.com/14541948/62943755-7af6e880-bddb-11e9-8666-1ec86fe9a93b.png)

What I see from here is that:
1) GTR gives always terrible esses;
2) There is a great variability for any other kind of site_model, tree (twin or true) and tree prior. No setting is immune to this error;
3) Trees with higher number of taxa (or high number of mutations, it is the same) usually yield very low esses, but small trees are prone to this problem too.
4) Any biological parameter (mu, nu, q) is totally not influential on the error.

I am very puzzled. Now I will try to look at the posterior trees.

**Comment by richelbilderbeek** [comment]
Best Issue comment ever! Don't we all love graphs!

Would it be a reasonable workaround to simply make the MCMC chain 2.5x longer?

Why 2.5? Because the lower quantile of the ESSes of the GTR model is approximately 80 (see figure), where we desire 200. Multiplying an ESS of 80 by 2.5 to get to 200 is what we need!

Do you think that solution would be good enough? When in doubt, I can easily start another razzo run. Personally, I am in doubt, as an ESS of 3 (which was in there) multiplied by 2.5 does not result in an ESS above 200.... Say 'Just run it and we'll see' would be OK :shipit: 

![naughty_site_model](https://user-images.githubusercontent.com/2098230/62949760-1477c780-bde7-11e9-8112-ea59ac398cba.png)

**Comment by Giappo** [comment]
We can get all the esses, calculate the 5% percentile and divide 200 by that number. Than multiply everything by that number.
According to the data we have the 5% percentile is 4, so we would need a factor of 50, i.e. if our chain used to be 1e6 we should try something around 5e7.
My fear is that the algorithm might get stuck in some kind of local minima, meaning that the trees will be all very similar to each other. How bad would it be, in case?

**Comment by richelbilderbeek** [comment]
> My fear is that the algorithm might get stuck in some kind of local minima, meaning that the trees will be all very similar to each other. How bad would it be, in case?

I cannot estimate how bad that would be, as it depends on how often it happens and if a workaround exists.

> EDIT: How much time does it take the full run now?

Approx 4 hours, for 2 replicates, crown age = 6, MCMC = 111k (see [razzo_project](https://github.com/richelbilderbeek/razzo_project#data) for the zipped results).

Again, Salvo-like work :+1:

**Comment by Giappo** [comment]
Another thing that I would be curious to try is to use a crown age = 10. How does time scale with number of replicates? They should be independent and then the process would be parallelizable, right?

**Comment by richelbilderbeek** [comment]
> Another thing that I would be curious to try is to use a crown age = 10. 

I think at a crown age of 7 things started to explode. I think it's a good idea to measure, will run this now.

> How does time scale with number of replicates? They should be independent and then the process would be parallelizable, right?

Linear (twice as much replicates takes twice as long on average). Each replicate has its own parallel job. Note that the `sshare` will go down, so more jobs will one day take longer to get to the front of the queue. My `sshare` is still at a whopping 0.227257!

**Comment by Giappo** [comment]
If the sshare is too low we can use my cluster account. Lemme know if it's needed.

**Comment by richelbilderbeek** [comment]
> If the sshare is too low we can use my cluster account. Lemme know if it's needed.

Will definitely do iff needed, thanks :+1:

**Comment by richelbilderbeek** [comment]
> Another thing that I would be curious to try is to use a crown age = 10.

See #238 :+1:

**Comment by richelbilderbeek** [comment]
For a crown age of 7, 3 out of 48 runs takes longer than 20 hours.

**Comment by richelbilderbeek** [comment]
I will try a run with all models...

**Comment by richelbilderbeek** [comment]
Time to close this Issue, I feel it has gone stale. I will open a new Issue if I need another Montelbano moment.
