### ISSUE TITLE
Make "collect_*" functions include path in the output, in place of parameters

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#233]
Progress:

Test written | Code written | Function name
---|---|---
 :ballot_box_with_check:   | :ballot_box_with_check:  | collect_esses.R
 :ballot_box_with_check:  | :ballot_box_with_check: | collect_marg_liks.R
 :ballot_box_with_check:  | :ballot_box_with_check: | collect_mbd_params.R
 :ballot_box_with_check:  | :ballot_box_with_check: | collect_n_taxa.R
 :ballot_box_with_check: | :ballot_box_with_check: | collect_nltt_stats.R

**Comment by Giappo** [comment]
Question:
In some function the dataframe has an entry called "gen_model" that could be either "mbd" or "bd".
In others there is, in its place, the entry "tree", that can be either "true" or "twin".
I suppose that if we want to reuse this function for raket you prefer to standardize to option 2. I will change it accordingly.
Just to let you know.

**Comment by richelbilderbeek** [comment]
> I suppose that if we want to reuse this function for raket you prefer to standardize to option 2

Yes, that option sounds fine (although there is this little voice that says: 'but I like it if the generative model is MBD, that it is called `mbd` :bird: )

**Comment by richelbilderbeek** [comment]
@Giappo: 4 our of 5 tests are already on develop! I marked them with: 

```
  skip("Issue 230, Issue #230")
```

Good luck!
