### ISSUE TITLE
Update pirouette figure

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#291]
This figure should be improved:

![workflow](https://user-images.githubusercontent.com/2098230/64865858-95222180-d63a-11e9-9a44-312ae9e8bbe3.png)

**Comment by richelbilderbeek** [comment]
These are the suggestions I remember from @Giappo:

![workflow](https://user-images.githubusercontent.com/2098230/64866028-f3e79b00-d63a-11e9-8cc9-a37034442b88.png)

**Comment by Giappo** [comment]
Things to update:
- [ ] Twin's clock and site model must be imported from G;
- [ ] Twin's tree prior is always BD?
- [ ] There are two different inference models that are picked: one for true, one for twin;

**Comment by richelbilderbeek** [comment]
> Twin's tree prior is always BD?

Yes, indeed. Alternatively, we *could* have used Yule as well. Point is: it is a constant/fixed.

**Comment by Giappo** [comment]
Ok, this is the current state. Confirm whether it is complete or there is something missing

![workflow4](https://user-images.githubusercontent.com/14541948/65602876-e8826100-dfa4-11e9-959f-84ea36fb15c0.png)

**Comment by Giappo** [comment]
I'll adjust the main text to be in accordance with this figure.

**Comment by richelbilderbeek** [comment]
It's AFAICS perfect. Good job :+1:

**Comment by Giappo** [comment]
I leave a proofread of the three modified sections (see below) to @richelbilderbeek . If he thinks that everything is ok, we can close this issue.

> * [x]  Pipeline figure;
> * [x]  Pipeline figure's caption;
> * [x]  Twinning section;

**Comment by richelbilderbeek** [comment]
Yup, will proofread Monday before 17:00.

**Comment by richelbilderbeek** [comment]
Proofreading

* [ ]  Pipeline figure;
* [x]  Pipeline figure's caption;
* [ ]  Twinning section;

**Comment by richelbilderbeek** [comment]
Done :+1:

**Comment by richelbilderbeek** [comment]
It's on the Overleaf as well :rainbow:
