### ISSUE TITLE
Determine optimal crown age

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#292]
... doing many MBD sims ... get clearer idea what the real mean n taxa is ...

**Comment by richelbilderbeek** [comment]
I quote:

> nu <- c(0, 0.5, 1.0, 2.0)

If this is really the case, re-open #296, as this one is done with  `nu <- c(0, 0.5, 1.0, 1.5, 2.0)`

The function `get_razzo_nus` is where the razzo nu's are.

**Comment by Giappo** [comment]
Results with crown_age == 7

# N Taxa

mu == 0
![n_taxas_plots_mu=0](https://user-images.githubusercontent.com/14541948/65689765-0071e780-e06e-11e9-8d24-424cf30daed8.png)

mu == 0.15
![n_taxas_plots_mu=0 15](https://user-images.githubusercontent.com/14541948/65689772-023bab00-e06e-11e9-9727-c18b73958558.png)

# Percentage MB Events

mu == 0
![percentage_mb_species_plots_mu=0](https://user-images.githubusercontent.com/14541948/65689796-0c5da980-e06e-11e9-95a3-69b1c4098282.png)

mu == 0.15
![percentage_mb_species_plots_mu=0 15](https://user-images.githubusercontent.com/14541948/65689801-0ff13080-e06e-11e9-87d1-69946163f33f.png)

The average number of taxa seems to low. Currently running the analysis again with crown_age == 8 on the peregrine cluster.

**Comment by richelbilderbeek** [comment]
Pretty!

**Comment by Giappo** [comment]
Simulations are running on the cluster for crown_ages = c(8, 9).

**Comment by Giappo** [comment]
We have data for crown_ages = c(7, 8, 9)

Everything can be found here: https://github.com/Giappo/mbd.TaxaAndMbness/tree/master/data

At the moment simulations are running also for crown_age = 10

**Comment by richelbilderbeek** [comment]
@Giappo: awesome work!

**Comment by Giappo** [comment]
Deprecated.
This is automatically solved when #322 is solved.
