### ISSUE TITLE
Fix or fixed mbd function

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#297]
Hi @Giappo, you asked me to take a look at an MBD function that wasn't properly exported. As I got *a* function to work on Travis, I think I did so, but that may be a different function. Did I get the desired function to work? If not, let me know :+1:

**Comment by Giappo** [comment]
Hi Richel,

I do not really remember what function it was. I suppose it's ok now? I'll close the issue. If the problem persists we can reopen it.
