### ISSUE TITLE
Put correct nus in manuscript

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#301]
From @Giappo:

> It's 0, 0.5, 1.0, 2.0

**Comment by richelbilderbeek** [comment]
I already put the right values in the code.

**Comment by Giappo** [comment]
I am a bit lost. Which one do we wanna use?

Last time at the meeting we talked about this:
![IMG_20190912_165208](https://user-images.githubusercontent.com/14541948/65766029-147b1f00-e12a-11e9-8df0-eace0240df3e.jpg)

But if I open the code I get this:
https://github.com/richelbilderbeek/razzo/blob/master/R/get_razzo_nus.R

**Comment by richelbilderbeek** [comment]
Nah, the code is outdated, the earlier quote at the top of the Issue as well as the picture are right.

That is why this is an Issue :grin:

**Comment by richelbilderbeek** [comment]
BTW, it *is* already correct on my branch. Will fix that branch *now*.

**Comment by richelbilderbeek** [comment]
The correct nus have reached [master](https://github.com/richelbilderbeek/razzo/blob/master/R/get_razzo_nus.R#L6).

Closing this Issue :+1:
