### ISSUE TITLE
Bug in pir_params$experiments[[1]]$beast2_options$beast2_path

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#308]
If you run test-create_fig_1 you'll get an error in:

>   plots <- create_fig_1( project_folder_name = get_razzo_path("razzo_project"))
 Error in value[[3L]](cond) : 
  'experiments' must be one experiment or a list of one or more experiments. 
Tip: use a list of 'create_experiment'. 
Error message: 'experiments[[1]] invalid.
Tip: use 'create_experiment' for each list element.
Error: 'beast2_options' must be valid BEAST2 options.
Tip: use 'beastier::create_beast2_options'.
Error: 'beast2_path' must exist. 
Actual path: '/home/p230198/.local/share/beast/lib/beast.jar'
Value: /home/p230198/GitHubs/razzo_project/data/0.2-0.15-1-0.1/1/mbd_gen.xml/home/p230198/GitHubs/razzo_project/data/0.2-0.15-1-0.1/1/mbd_gen.log/home/p230198/GitHubs/razzo_project/data/0.2-0.15-1-0.1/1/mbd_gen.trees/home/p230198/GitHubs/razzo_project/data/0.2-0.15-1-0.1/1/mbd_gen.xml.state1NAFALSETRUE/home/p230198/.cache/fileb60e113a8a7a/home/p230198/.local/share/beast/lib/beast.jarFALSE
Value: list(model_type = "generative", run_if = "always", do_measure_evidence = TRUE)list(site_model = list(name = "JC69", id = NA, gamma_site_model = list(gamma_cat_count = "0", gamma_shape = 

I digged and I found that it all comes down to this:

> pir_params$experiments[[1]]$beast2_options$beast2_path
[1] "/home/p230198/.local/share/beast/lib/beast.jar"

Clearly this cannot work, unless you are on the cluster with the p230198 account. In all other cases, like while testing, this cannot work.
Is this related to the bug you found when working on win platforms @richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
Thanks for the awesome report! This is definitely my doing! Will fix today before 14:00, unless you want me to do it faster.

**Comment by richelbilderbeek** [comment]
Actually, will fix *now*
