### ISSUE TITLE
Decide: do run with Yule generative and twin tree for zero extinction rate?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#316]
* [WIP]: this Issue is a 'Work in Progress' and not complete yet

I quote from `razzo_article`:

> For the MBD model without extinction, [...]
we could have picked the Yule tree prior [...]

I wonder, shouldn't we pick the Yule tree prior as a generative tree prior and/or as the twin tree?

**Comment by richelbilderbeek** [comment]
Sent email to @Giappo:

> razzo approve/suggest: use Yule as the generative tree prior for settings with zero extinction rate
>
> 9 January 2020 07:43 3 KB
> From: Richel Bilderbeek
> To: Giovanni Laudanno
> 
> [...]
> 
> I need your approval/suggestion of using the Yule tree model as a prior
in the `razzo` settings with zero extinction rate.
> 
> Currently, in razzo, we always use a BD tree model as the generative tree
prior. This is then compared with some candidate models, some of which
with a Yule tree prior.
> 
> I'd say, this is correct for non-zero extinction rate, but incorrect for
an extinction rate of zero. For settings without extinction, I suggest to
use a Yule tree model as a generative prior and use a BD tree model in
the candidate models.
> 
> So, do you approve?
> 
> * 1. Yes, I approve
> * 2. No, I need more information/options: we'll discuss this on Friday
> 
> [...]

**Comment by Giappo** [comment]
Keep it as it is :+1:
