### ISSUE TITLE
Call 'DDD::bd_ML' with which condition?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#32]
`raz_create_bd_tree` uses `DDD::bd_ML` with a certain conditioning.

Check if it is indeed the right one. Document that in the article.

**Comment by richelbilderbeek** [comment]
Here is the exact conditioning:

```
    # TODO and NOTE: Issue #32: should cond be 1 or 2?
    bd_pars <- DDD::bd_ML( # nolint
      brts = abs(mbd_brts),
      cond = 2,
      initparsopt = c(lambda, mu),
      idparsopt = 1:2,
      missnumspec = 0,
      tdmodel = 0,
      btorph = 1,
      soc = soc
    )
```

I think @Giappo would enjoy checking this, so I take the liberty to assign him. If not, let me knew and/or unassign.

**Comment by Giappo** [comment]
@richelbilderbeek 

I quote Rampal's email (from 11th of October):

"2. Compute the Maximum Likelihood parameters (lambda, mu) under the CR
model (constant-rate birth-death model) for this tree, using
conditioning on crown age and number of tips. In DDD this is cond = 2. (*)"

I think cond==2 is the right answer. Close the issue if you agree.

**Comment by richelbilderbeek** [comment]
Agree!

Closing the Issue :+1:
