### ISSUE TITLE
Determine optimal parameter settings

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#322]
# Parameter settings change

I had a meeting with @rsetienne last week and showed him the plots for n_taxa and mbness (see at the end).

I told him that some parameter settings produce these huge tree that cannot be analyzied in the 10 days. The reason is that the variability among the parameter settings is huge, so we came to the conclusion that's better to change the parameter settings too.

1. We do not need to vary q if nu == 0. Trees are likely to be the same;
2. He suggested to remove (nu = 2, q = 0.15) and (nu = 2, q = 0.2) because, looking at the plots, these ones are likely to create the trees we cannot analyze;
3. At the same time we should try to get more taxas (optimally in the interval [10, 20]) for the smallest trees. This is because if trees are too small we cannot get enough information out of them. We can do two things:
 3a. Increase the difference lambda - mu. We can, for example, set lambda == 0.3 or reduce mu == 0.15 to be mu == 0.10;
 3b. Increase the crown age. This will increase also the setting with high mbness. He suggested crown_age == 8 or crown_age == 9;

I also think we can do this:

4. Establish what's the maximum number of tips we can take. It appears to be 400 at the moment. Then we impose that for each parameter settings no more than 5% (or any other arbitrary threshold) of the trees must exceed this value;

# Plots for n_taxa and percentage_mbness for crown_age == c(8, 9)

### mu == 0
![crown_age=8-n_taxas_plots-mu=0](https://user-images.githubusercontent.com/14541948/66312626-5158ca00-e911-11e9-88fa-96811964ff44.png)
![crown_age=8-percentage_mb_species_plots-mu=0](https://user-images.githubusercontent.com/14541948/66312637-56b61480-e911-11e9-8559-d21c1301f347.png)

# mu == 0.15
![crown_age=8-n_taxas_plots-mu=0 15](https://user-images.githubusercontent.com/14541948/66312683-66cdf400-e911-11e9-836d-c9f4a425617b.png)
![crown_age=8-percentage_mb_species_plots-mu=0 15](https://user-images.githubusercontent.com/14541948/66312692-69c8e480-e911-11e9-9e46-516e5f8cb38f.png)

### mu == 0
![crown_age=9-n_taxas_plots-mu=0](https://user-images.githubusercontent.com/14541948/66312761-82d19580-e911-11e9-8e66-8c0e7706577d.png)
![crown_age=9-percentage_mb_species_plots-mu=0](https://user-images.githubusercontent.com/14541948/66312771-86fdb300-e911-11e9-84e6-2f7b8ca104b2.png)

# mu == 0.15
![crown_age=9-n_taxas_plots-mu=0 15](https://user-images.githubusercontent.com/14541948/66312784-8ebd5780-e911-11e9-8db3-197bcae83eec.png)
![crown_age=9-percentage_mb_species_plots-mu=0 15](https://user-images.githubusercontent.com/14541948/66312793-941aa200-e911-11e9-9065-e434a36957dc.png)

**Comment by richelbilderbeek** [comment]
I guess we then both work on this :+1:?

**Comment by Giappo** [comment]
> I guess we then both work on this 👍?

Yes, but we should take decisions with reference to the 4 points we mentioned in the issue.

**Comment by richelbilderbeek** [comment]
Definitely! Will look in more detail tomorrow at 11:15 and blend you (awesome!) pictures and ideas with mine.

**Comment by Giappo** [comment]
Link to the repo with the data
https://github.com/Giappo/mbd.TaxaAndMbness/tree/master/data

**Comment by richelbilderbeek** [comment]
Minor note: I think 'percentage' is misleading is this context, as it suggest values go from zero to one hundred. Taking a look at the code, I see no multiplication by 100:

```r
> mbd::count_percentage_mb_events
function (brts) 
{
    mb_species <- count_n_mb_events(brts)
    if (mb_species == 0) {
        percentage_mb_species <- 0
    }
    else {
        births <- brts2time_intervals_and_births(brts)$births
        n_species <- sum(births)
        percentage_mb_species <- mb_species/n_species
    }
    percentage_mb_species
}
```

Therefore, I think 'fraction' or 'proportion' would have been a better name.

**Comment by richelbilderbeek** [comment]
> 1. We do not need to vary q if nu == 0. Trees are likely to be the same

Fully agree, let's get rid of these duplicates! Created #323 to do this.

**Comment by richelbilderbeek** [comment]
I think point 2, 3 and 4 are excellent descriptions of the trade-offs we face!

I've summarized them here, and re-ordered them:

> 2.  [To fix too big trees] remove (nu = 2, q = 0.15) and (nu = 2, q = 0.2) 
> 4. [To fix too big trees] impose that for each parameter settings no more than 5% [...] exceed this [maximum number of trees we can analyse]
> 3. [To fix too small trees]:
>   3a. Increase the difference lambda - mu [...]
>   3b. Increase the crown age [...]

Doing so again

 * 2 and 4: [Too big trees]
 * 3a and 3b. [Too small trees]

From there, it may be easier to conclude that the problem of having too big trees is the more important problem: we cannot analyse too big trees (we can analyse small trees and, sure, this will end up in the discussion).

From there, whatever we choose, point 4 (95% of all trees must be small enough to be analysed) must hold.

But I do think one constraint is missing:

 * 5. We want a nice spread in MBDness and we want some settings with a strong MBD effect

5 is in conflict with 2 (removing the most speciose and MBD settings), but I personally think 5 is more important, as it is our research question. with the current setting we get an average percentage of MBDness of (100 * ([14](https://raw.githubusercontent.com/Giappo/mbd.TaxaAndMbness/master/data/crown_age_7/crown_age%3D7-percentage_mb_species_plots-mu%3D0.15.png) + [19](https://raw.githubusercontent.com/Giappo/mbd.TaxaAndMbness/master/data/crown_age_7/crown_age%3D7-percentage_mb_species_plots-mu%3D0.png)) / 2 =) 15.5%
which I think is good enough. Removing the strongest MBD settings is -I think- a bad idea.

This would make me conclude that our current settings are the best we can do. 

Maybe we can increase the crown age (I would be in favor), but except for that I think we should keep in the spread of MBDness including the defensible too small trees in some settings.

Do you agree on this reasoning?

**Comment by richelbilderbeek** [comment]
Just for completeness: [overview of all pilot experiments](https://github.com/richelbilderbeek/razzo_project/blob/richel/overview.md)

**Comment by richelbilderbeek** [comment]
Another vital points: either most ESSes must be above 200, or the average ESS must be above 200.

To guide our discussion today, I created a helpful table:

|date     |most_runs_pass |mean_ess_good |most_ess_good |
|:--------|:--------------|:-------------|:-------------|
|20190808 |TRUE           |TRUE          |FALSE         |
|20190815 |TRUE           |TRUE          |FALSE         |
|20190829 |FALSE          |TRUE          |FALSE         |
|20190903 |TRUE           |TRUE          |FALSE         |
|20190904 |TRUE           |TRUE          |FALSE         |
|20190905 |TRUE           |TRUE          |FALSE         |
|20190906 |TRUE           |TRUE          |FALSE         |
|20190908 |TRUE           |TRUE          |FALSE         |
|20190910 |TRUE           |TRUE          |FALSE         |
|20190915 |FALSE          |TRUE          |FALSE         |
|20190918 |TRUE           |TRUE          |FALSE         |
|20190923 |TRUE           |TRUE          |FALSE         |
|20191006 |TRUE           |TRUE          |FALSE         |
|20191007 |TRUE           |TRUE          |FALSE         |

I think this table will help us getting to the least evil of all combinations :+1:

**Comment by Giappo** [comment]
@richelbilderbeek 
I think you should take a look at this...

![crown_age=8-percentage_mb_species_plots-mu=0](https://user-images.githubusercontent.com/14541948/66654934-8760bb80-ec3b-11e9-9cd3-967ae1c2a92c.png)
![crown_age=8-n_mb_species_plots-mu=0 1](https://user-images.githubusercontent.com/14541948/66654935-8760bb80-ec3b-11e9-96f1-867012e1b727.png)
![crown_age=8-n_mb_species_plots-mu=0](https://user-images.githubusercontent.com/14541948/66654936-8760bb80-ec3b-11e9-933b-b9d4d7269630.png)
![crown_age=8-n_taxas_plots-mu=0 1](https://user-images.githubusercontent.com/14541948/66654937-8760bb80-ec3b-11e9-819c-698f5ff75f3c.png)
![crown_age=8-n_taxas_plots-mu=0](https://user-images.githubusercontent.com/14541948/66654938-8760bb80-ec3b-11e9-90f4-19945111ed82.png)
![crown_age=8-percentage_mb_species_plots-mu=0 1](https://user-images.githubusercontent.com/14541948/66654940-87f95200-ec3b-11e9-8cdb-1bd56b57f3f5.png)

As usual: link to the [data](https://github.com/Giappo/mbd.TaxaAndMbness/tree/master/data) in the repo.

**Comment by richelbilderbeek** [comment]
I feel the Giappo params are great. Let's close this Issue :+1:
