### ISSUE TITLE
Check ESSes versus MBD params

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#327]
Tip: use [https://github.com/richelbilderbeek/razzo_project/blob/richel/scripts/90_collect_run_times.R](https://github.com/richelbilderbeek/razzo_project/blob/richel/scripts/90_collect_run_times.R) (on Richel's branch) to see how the overview and verdict are now created.

**Comment by richelbilderbeek** [comment]
Will do so tomorrow/Thursday

**Comment by richelbilderbeek** [comment]
To check, do, in the root folder of this project:

```
Rscript scripts/issue_327.R
```

**Comment by richelbilderbeek** [comment]
Results can be found at [https://github.com/richelbilderbeek/razzo_pilot_results/blob/master/mbd_vs_ess.md](https://github.com/richelbilderbeek/razzo_pilot_results/blob/master/mbd_vs_ess.md).

**Comment by richelbilderbeek** [comment]
Added plot:

![issue_327](https://user-images.githubusercontent.com/2098230/73453289-02292000-436c-11ea-85b3-279d2a1b95ac.png)

```r
library(ggplot2)

ggplot(df, aes(x = nu, y = ess_likelihood, color = as.factor(q))) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = mean(df[ df$q == 0.0,  ]$ess_likelihood), col = "red") +
  ggtitle("horizontal line is mean for q == 0.0") +
  ggsave("~/issue_327.png")
```

**Comment by richelbilderbeek** [comment]
Only use those runs with less than 1000 ESSes measured.

![issue_327](https://user-images.githubusercontent.com/2098230/73453688-d9edf100-436c-11ea-96d3-e7bd7c718fde.png)

**Comment by richelbilderbeek** [comment]
Hi @Giappo,

I've created the data you requested and did some -hopefully helpful- plotting.

Raw data can be found at [https://github.com/richelbilderbeek/razzo_pilot_results/blob/master/mbd_vs_ess.md](https://github.com/richelbilderbeek/razzo_pilot_results/blob/master/mbd_vs_ess.md), or use the CSV of the same name.

What do you think of these results?
