### ISSUE TITLE
Make verdict per parameter setting

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#328]
Tip: use [https://github.com/richelbilderbeek/razzo_project/blob/richel/scripts/90_collect_run_times.R](https://github.com/richelbilderbeek/razzo_project/blob/richel/scripts/90_collect_run_times.R) (on Richel's branch) to see how the overview and verdict are now created.

**Comment by richelbilderbeek** [comment]
Will do so tomorrow/Thursday

**Comment by richelbilderbeek** [comment]
Uh, I think I did, judging by the files called 'verdict'. Closing this :+1:
