### ISSUE TITLE
Add parameter for site model

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#33]
Also upgrade the function that uses a site model.

```
testit::assert(parameters$site_model %in% c("jc69", "gtr"))
```

**Comment by richelbilderbeek** [comment]
Labeled with:

```
  skip("TODO: #33: Add parameter for site model")
```

@Giappo: I think this one for you! I hope you'll enjoy making the tests pass. If not, let me know :+1:

**Comment by Giappo** [comment]
Everything should be in place. I cannot test it because I cannot run the inference on Windows.
Check on Linux. If it works (as I expect), move the issue to Done.

**Comment by richelbilderbeek** [comment]
@Giappo: well done! I've seen [your commit](https://github.com/richelbilderbeek/razzo/commit/33be1d023bbf4d7b9d9910042cf2abc0882f6552).

About testing: I designed the tests for this Issue to be able to actually check. Whatever OS, one can check if a data structure is created correctly. Just run all the tests and if everything is good, life is good :rainbow:

As the tests fail, I am going to put you back on this Issue. @lintr-bot has some feedback on it. Good luck :+1:

**Comment by Giappo** [comment]
Solved
