### ISSUE TITLE
Add parameter for clock model

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#34]
Also upgrade the function that uses a clock model.

```
# s: strict
# rln: relaxed log-normal
testit::assert(parameters$clock_model %in% c("s", "rln"))
```

**Comment by richelbilderbeek** [comment]
Added tests labeled with:

```
skip("TODO: #34: Add parameter for clock model")
```

@Giappo: I think this one for you! I hope you'll enjoy making the tests pass. If not, let me know :+1:

**Comment by Giappo** [comment]
Hi Richel,

I am using beautier::create_clock_model(name, id). What's the purpose of 'id'? Do we actually need it or can i set it to a meaningless fixed value (e.g. 'id'=1 everywhere)?

**Comment by Giappo** [comment]
Ok, it seems to be not important if you call the specific functions for the specific models.
CLOSED

**Comment by Giappo** [comment]
Everything should be in place. I cannot test it because I cannot run the inference on Windows.
Check on Linux. If it works (as I expect), move the issue to Done.

**Comment by richelbilderbeek** [comment]
@Giappo: well done! I've seen [your commit](https://github.com/richelbilderbeek/razzo/commit/33be1d023bbf4d7b9d9910042cf2abc0882f6552).

About testing: I designed the tests for this Issue to be able to actually check. Whatever OS, one can check if a data structure is created correctly. Just run all the tests and if everything is good, life is good :rainbow:

As the tests fail, I am going to put you back on this Issue. @lintr-bot has some feedback on it. Good luck :+1:

**Comment by Giappo** [comment]
Solved
