### ISSUE TITLE
Give last info for presentation

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#353]
From Giappo:

> I'd like to add another slide with esses and percentage of successful calculations (t < 10 days), for each parameter setting. There is an empty slide for that.
If you manage to get those results in time you can add the figures (or send me the data so I can produce the figures). Otherwise I will stick to what it's already there.

**Comment by richelbilderbeek** [comment]
Put CSVs at [https://github.com/richelbilderbeek/razzo_project/tree/richel](https://github.com/richelbilderbeek/razzo_project/tree/richel), sent email to @Giappo.

If he needs something more, I'll create a new Issue.

Closing this one :+1:

**Comment by Giappo** [comment]
The figures needed (or at least the data to produce it) show (a) esses and (b) percentages of successful runs for each parameter setting (e.g. nu = 0,q=0; nu = 0.5, q = 0.1; etc) in the "Giappo" setting.
Basically like the ones we [already have](https://github.com/Giappo/mbd.SimTrees/tree/master/inst/extdata/la%3D0.2-mu%3D0%2C0.1-nu%3D0%2C0.5%2C1%2C1.5-q%3D0.1%2C0.15%2C0.2-age%3D8) for n_taxa and percentage_mbness but with these other stats.

If it's not possible it is fine anyways. The presentation will look ok even without it.
If it's too much work for you or you're busy ot it is too late you can close the issue.
:rainbow:

**Comment by richelbilderbeek** [comment]
Ah, I am sorry I overlooked 'for each parameter setting'. Will try if I can do so tonight, I give myself 50% chance. I will let you know whatever the outcome at approx 20:30.

**Comment by richelbilderbeek** [comment]
There it is:

[detailed_overview.zip](https://github.com/richelbilderbeek/razzo/files/3730620/detailed_overview.zip)

**Comment by richelbilderbeek** [comment]
@Giappo: I did it!

Closing the Issue. If there's something missing, feel encouraged to tell me and re-open this Issue. Will take a look tomorrow :+1:

**Comment by Giappo** [comment]
Sorry @richelbilderbeek but the parameter setting is the wrong one.

These are the correct ones:

https://raw.githubusercontent.com/Giappo/mbd.SimTrees/master/inst/extdata/la%3D0.2-mu%3D0%2C0.1-nu%3D0%2C0.5%2C1%2C1.5-q%3D0.1%2C0.15%2C0.2-age%3D8/n_mb_0.png
  
https://raw.githubusercontent.com/Giappo/mbd.SimTrees/master/inst/extdata/la%3D0.2-mu%3D0%2C0.1-nu%3D0%2C0.5%2C1%2C1.5-q%3D0.1%2C0.15%2C0.2-age%3D8/n_mb_0.1.png

**Comment by richelbilderbeek** [comment]
Dang, I hoped you didn't notice :sunglasses:

I just used the simulation results I had available (which does contain some crowng age == 8 settings). Too bad, will not deliver that data today: it was fun to have a gazillion challenges at a time, but today I'll focus on our presentation :+1:

**Comment by richelbilderbeek** [comment]
This has no priority anymore, so I close the Issue. I do think *en passant* I fixed some other Issues...
