### ISSUE TITLE
Vote for pirouette logo

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#358]
Currently, pirouette has two logos:

![pirouette_logo](https://user-images.githubusercontent.com/2098230/68312413-4d0c0200-00b3-11ea-8a5a-d14d0e90133f.png)

![pirouette_logo_2](https://user-images.githubusercontent.com/2098230/68312414-4d0c0200-00b3-11ea-8294-f652e60694b0.png)

@Giappo: do you have a preference?

**Comment by Giappo** [comment]
I vote for the 1st one!
💃

**Comment by richelbilderbeek** [comment]
First one it is. Thanks!
