### ISSUE TITLE
Gather info: Proportion invariant in DNA: 0.0, 0.5 or estimate?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#369]
Note to self now, will discuss with Giappo.

![screen](https://user-images.githubusercontent.com/2098230/70222804-ce09f800-174a-11ea-9e68-248b109f56eb.png)

**Comment by richelbilderbeek** [comment]
From my Progress Report:

> When reading Revell et al., 2005, for my thesis, I saw that they
set and specified a proportion of invariant sites. Within `razzo`
we do set a proportion of invariant sites just yet. We can pick
between (1) setting this proportion to a fixed/known value of 0.5, or
(2) let it be estimated. 

 * Revell, Liam J., Luke J. Harmon, and Richard E. Glor. "Under-parameterized model of sequence evolution leads to bias in the estimation of diversification rates from molecular phylogenies." Systematic Biology 54.6 (2005): 973-983.

**Comment by richelbilderbeek** [comment]
I would be in favor of setting the known value to 0.5, as this simply *is* the case.

**Comment by richelbilderbeek** [comment]
> (No subject)
>
> 6 January 2020 14:42 3 KB
> From: Richel Bilderbeek
> To: Giovanni Laudanno
>
> [...]
>
> I need your suggestion/approval on this razzo issue (see also [1]).
> 
> Currently, our inference implicitly assumes that all our DNA sites are variant sites, i.e. they could have been hit by a mutation. In reality, however, we set the crown age as such to have 50% of the sites to be variant on average, similar to [2]. That article, however, also specifies this information in the inference.
> 
> I suggest to do the same.
> 
> What do you think?
> 
>  * 1. Yes, good idea
>  * 2. Need more info/options
> 
> [...]
> 
>  * [1] https://github.com/richelbilderbeek/razzo/issues/369
>  * [2] Revell, Liam J., Luke J. Harmon, and Richard E. Glor. "Under-parameterized model of sequence evolution leads to bias in the estimation of diversification rates from molecular phylogenies." Systematic Biology 54.6 (2005): 973-983.

**Comment by richelbilderbeek** [comment]
Will be decided on meeting Friday/tomorrow.

**Comment by Giappo** [comment]
@richelbilderbeek, take a look :+1:

**Comment by Giappo** [comment]
@Giappo will ask people

**Comment by richelbilderbeek** [comment]
I quote from [https://github.com/rbouckaert/DeveloperManual#proportion-invariable-sites](https://github.com/rbouckaert/DeveloperManual#proportion-invariable-sites):

> Since each site evolves with non-zero rate, use of proportion invariable sites is modelling the process badly, and therefore not recommended.

Therefore, @Giappo's instincts were superior and we can keep everything as it is :rainbow:
