### ISSUE TITLE
Decide: DNA sequence length: 1000 or 5000?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#370]
Note to self first, will discuss with Giappo later.

[In this article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6421065/)

```
@article{sarver2019choice,
  title={The choice of tree prior and molecular clock does not substantially affect phylogenetic inferences of diversification rates},
  author={Sarver, Brice AJ and Pennell, Matthew W and Brown, Joseph W and Keeble, Sara and Hardwick, Kayla M and Sullivan, Jack and Harmon, Luke J},
  journal={PeerJ},
  volume={7},
  pages={e6334},
  year={2019},
  publisher={PeerJ Inc.}
}
```

in [SupMat 2 (PDF)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6421065/bin/peerj-07-6334-s002.pdf) they find:

![screen01](https://user-images.githubusercontent.com/2098230/70226304-e7ae3e00-1750-11ea-858d-916de9d9fa29.png)

If we are convinced, we could use 5k as well.

**Comment by richelbilderbeek** [comment]
The reason 5k is used, is from [1], where estimated speciation rates are not getting better after 5k nucleotides. Because razzo does not estimate speciation rates, we can AFAICS use 1k nucleotides regardless (as the experiment takes up a lot of runtime) and mention it someplace.


 * [1] Wertheim, Joel O., and Michael J. Sanderson. "Estimating diversification rates: how useful are divergence times?." Evolution: International Journal of Organic Evolution 65.2 (2011): 309-320.

**Comment by richelbilderbeek** [comment]
Sent email to @Giappo:

> razzo approve/suggest: DNA sequence length
>
> 6 January 2020 14:55 3 KB
> From: Richel Bilderbeek
> To: Giovanni Laudanno
>
> [...]
>
> I need your approval/suggestion of the DNA sequence length we use in razzo.
> 
> Currently, in razzo, we use a DNA sequence length of 1k. A similar research [2] uses a DNA sequence length of 5k, because in [3] they found that using a DNA alignment longer than 5k, the estimation of the speciation rate does not improve.
> 
> I'd say, because we do not estimate a speciation rate, we can ignore (yet mention) the practice of using 5k nucleotides, to gain more replicates instead.
> 
> So, do you approve?
> 
>  * 1. Yes, I approve
>  * 2. No, I need more information/options
> 
> [...]

**Comment by richelbilderbeek** [comment]
Will be decided on meeting Friday/tomorrow.

**Comment by Giappo** [comment]
Yes I approve.
