### ISSUE TITLE
collect_esses must ignore ESSes of marginal likelihood estimations

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#385]
Three months ago, the ESSes were OK:

![20191017](https://user-images.githubusercontent.com/2098230/72965818-92d88c80-3dbd-11ea-97ab-183812a804df.png)

This morning, the ESSes were bad:

![20200123](https://user-images.githubusercontent.com/2098230/72965819-92d88c80-3dbd-11ea-8956-90eec5da7b9d.png)

**Comment by richelbilderbeek** [comment]
Hmm, the `collect_esses` function appears to be messed up:

![1](https://user-images.githubusercontent.com/2098230/72967151-f0220d00-3dc0-11ea-866f-9236aa147b00.png)

**Comment by richelbilderbeek** [comment]
My hypothesis:

```r
  # raztr has run one setting ..."
  #  - with two seeds
  #  - for true and twin tree
  #  - for generative and candidate
  # This is 2x2x2 Effective Sample Sizes
  #
  # Hypothesis: the logs for the marginal likelihoods are also read.
```

**Comment by richelbilderbeek** [comment]
I think @Giappo would be up for this...

**Comment by richelbilderbeek** [comment]
Look for 

```r
skip("#385")
```

to see the test that fails, but should pass.

**Comment by Giappo** [comment]
> Look for
> 
> ```r
> skip("#385")
> ```
> 
> to see the test that fails, but should pass.

ctrl+shift+f for skip("#385") doesn't return anything. Are you sure?

**Comment by richelbilderbeek** [comment]
Yup, I am sure :grin: 

![yesy](https://user-images.githubusercontent.com/2098230/72974780-e6ec6c80-3dcf-11ea-85a8-33ca3c7c5896.png)

Don't forget to merge develop to your branch :innocent:

**Comment by richelbilderbeek** [comment]
Also, one can search the repo itself:

![gh](https://user-images.githubusercontent.com/2098230/72975991-08e6ee80-3dd2-11ea-927d-4fb9c5bb838b.png)

Life is great!

**Comment by Giappo** [comment]
Ok, one important question:
What are the characteristics that defines the files we want to use.
In this case they should be mbd.best.log, mbd_gen.log, mbd_best_twin.log, mbd_gen_twin.log.
I suppose, though, that we should define a better criterion than just impose such filenames as this will be eventually used (at least) also in raket.
So I ask you: how would you identify the correct files?

**Comment by Giappo** [comment]
One criterion could be that if a filename contains the word "evidence" it must not be considered.
This, though, prevents only the evidence files to be loaded. Is it enough?

**Comment by richelbilderbeek** [comment]
:+1:
