### ISSUE TITLE
Do https://github.com/richelbilderbeek/pirouette/issues/378

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#388]
See [https://github.com/richelbilderbeek/pirouette/issues/378](https://github.com/richelbilderbeek/pirouette/issues/378).

I added this is a duplicate, so it shows up in the `razzo` Project page.

**Comment by richelbilderbeek** [comment]
I think @Giappo would enjoy this one :+1:

**Comment by Giappo** [comment]
The original one is marked as done. Close.
