### ISSUE TITLE
Send data again, so I can reproduce the figure

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#394]

**Comment by richelbilderbeek** [comment]
Done, see emails bewow.


> Raw data again
>
> 13 February 2020 14:44 11 KB
> From: Richel Bilderbeek
> To: Giovanni Laudanno
> 
> [...] Here is how to create figure 1:
> 

```r
# Path to razzo_project folder
project_folder_name <- "/media/richel/D2B40C93B40C7BEB/razzo_project/razzo_project_20200204"

# Get figure 1
razzo::create_fig_1(project_folder_name)

# Save figure 1 to '[razzo_project folder]/results/fig_1.png' (or something similar)
razzo::create_fig_1_file(project_folder_name)
```

> It takes looooooooong on my computer. I do not know how long exactly, as it runs out of memory first. I hope/bet your computer is superior to mine though :-)

> ---------- Forwarded message ----------
> From: Richel Bilderbeek [...]
> Date: 4 February 2020 at 17:17:57 +01:00
> Subject: Re: better plotting functions? I don't know
> To: Giovanni Laudanno [...]


> Is there an easy way to access the raw data for this test?

'Easy' not, the data is big!

Raw data is here:

>  * Download [http://richelbilderbeek.nl/razzo_project_20200204_unfinished.zip](http://richelbilderbeek.nl/razzo_project_20200204_unfinished.zip)

Aggregrated data can be found here:

>  * Download results: [http://richelbilderbeek.nl/razzo_project_20200204_unfinished_results.zip](http://richelbilderbeek.nl/razzo_project_20200204_unfinished_results.zip)
