### ISSUE TITLE
DDD::L2phylo gives unclear error

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#43]
In the function `raz_create_bd_tree`, one of the last lines is to convert the BD L matrix to a phylogeny:

```
> DDD::L2phylo(bd_l_matrix)
```

This gives the unclear error:

```
Error in `[<-.data.frame`(`*tmp*`, j, 1:3, value = numeric(0)) : 
  replacement has 0 items, need 3
```

I've added a fake return value until this is fixed:

```
  # TODO: Issue #43: DDD::L2phylo gives unclear error
  if (1 == 2) {
    return(DDD::L2phylo(bd_l_matrix))
  }
  # FAKE
  mbd_tree
```

Yup, for now it simply returns the MBD tree :rainbow:

**Comment by Giappo** [comment]
DONE
