### ISSUE TITLE
raz_create_mbd_alignment must calculate its mutation rate

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#48]
AFAICS, `raz_create_mbd_alignment` is perfectly capable of calculating its mutation rate.

At the moment, it uses a mutation rate from an input file:

```
raz_create_mbd_alignment <- function(
  parameters, mbd_tree
) {
  # ...
  mutation_rate <- parameters$mbd_mutation_rate

  # ...
}
```

 * The mutation rate should be calculated as in the comments in the code and/or according to as described in the article
 * The mutation rate can be removed from parameter file creation

**Comment by richelbilderbeek** [comment]
@Giappo: I think this one (and #49 as well) is one for you! I cannot write tests for this, so I hope the description is clear. Are you up for this Issue?

**Comment by richelbilderbeek** [comment]
I took the liberty to assign @Giappo. Just unassign if disagree :+1:

**Comment by richelbilderbeek** [comment]
>  Is this really what we want?

Definitely! The goal of `razzo` is to do the experiment as described in the manuscript, and nothing more than that. 

There is an [acronymn, 'YAGNI'](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it), for this :+1:

**Comment by richelbilderbeek** [comment]
Will move Issues to 'To Do' column again.

**Comment by Giappo** [comment]
Now it works
