### ISSUE TITLE
check that the inference of lambda and mu provided by bd_ML is decent.

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#52]
bd_ML sometimes gives us back some weird lambda and mu. let's be sure they are right

**Comment by Giappo** [comment]
For seed = 1 we have that
bd_pars <- DDD::bd_ML( # nolint
      brts = abs(mbd_brts),
      cond = 2, #conditioning on stem or crown age and on the total number of extant taxa (including missing species)
      initparsopt = c(lambda, mu),
      idparsopt = 1:2,
      missnumspec = 0,
      tdmodel = 0,
      btorph = 1,
      soc = soc
    )
returns bd_pars = c(lambda = 0.539926, mu = 0.540032).
This is scary as the birth death model should only consider cases where lambda < mu (or, at max, lambda = mu, which is critical but is possible to deal with it).

**Comment by richelbilderbeek** [comment]
According to Giovanni, Rampal suggests to use:

```
cond = 1, #conditioning on [...] crown age
```

instead of:

```
cond = 2, #conditioning on stem or crown age and on the total number of extant taxa (including missing 
```

Argument sounded OK, need to think about it still.

**Comment by richelbilderbeek** [comment]
Moved to #129, closing this one.
