### ISSUE TITLE
Fix mbd package

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#63]
Currently, `mbd` is in the process of an overhaul. `razzo` failed because of that overhaul being completed only partially.To fix that, `razzo` now depends on the last `master` version:

```
devtools::install_github("Giappo/mbd", ref = "d1b85b44cbcc28c20376708d8b6dee87298fa43d")
```

I suggest the following order to overhaul mbd:

 * [ ] fix `mbd` on `develop`
 * [ ] if passes, merge with master
 * [ ] update razzo

**Comment by richelbilderbeek** [comment]
I'll assign Giappo, as he's the package author. Of course, I'll help iff needed.

**Comment by Giappo** [comment]
Travis gave us its blessing.
I think we can CLOSE this.
