### ISSUE TITLE
Make possible to build vignette on windows

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#70]
I need to check the package on my local machine to have a hope it'll work on travis and appveyor. Problem is that vignette building will always fail. I suppose is due to those part of the pipeline that are impossible to run on my OS.
Maybe adding some "if (rappdirs::app_dir()$os != "win") {" here and there can fix it?

**Comment by richelbilderbeek** [comment]
This Issue will follow from #64 ('Add AppVeyor'), which was created for exactly this reason.

**Comment by richelbilderbeek** [comment]
`razzo` builds successfully under Windows now, [accroding to AppVeyor](https://ci.appveyor.com/project/richelbilderbeek/razzo/builds/20224124). One cannot run BEAST2 on Windows, so the vignette uses pre-fab data instead. 

@Giappo: I assume the Issue is fixed?

**Comment by Giappo** [comment]
I've seen you removed all the "if (sys == "win")" and I can still build the vignette. I think we can consider this closed.

**Comment by Giappo** [comment]
Sorry, i meant CLOSED.
