### ISSUE TITLE
Remove all the instances of ape::branching.times

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#71]
Remove all the instances of ape::branching.times. Branching times should always be obtained from the L table using the function DDD::L2brts. This is important because sometimes branching.times fails to recognize multiple events and instead creates events that differ of something like 1e-13

**Comment by Giappo** [comment]
We can actually leave them only in the case where we use it to find the crown age (which is never gonna be a multiple birth).

**Comment by richelbilderbeek** [comment]
I assume this is correct. Will check in 'Launch' phase of Project. Closing the Issue :dancing_men: :dancing_women:
