### ISSUE TITLE
Add safety mechanisms to the functions mbd::brts2time_intervals_and_births and mbd::mbd_sim

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#72]
Add safety mechanisms to the functions mbd::brts2time_intervals_and_births and mbd::mbd_sim.
Branching times have to be rounded to the precision of 1e-7. Since the unit is a million year we can reasonably consider that if the difference is 1e-7*million year = 1 month, two events can really be considered simultaneous. This is important because prevent any kind of errors when we have to detect multiple events.

**Comment by richelbilderbeek** [comment]
I assume you are right, will check in 'Launch' phase of the Project. Closing the Issue :last_quarter_moon_with_face:
