### ISSUE TITLE
Fix 'unused argument n_0/soc'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#73]
`mbd` transitioned to using `n_0` for the initial number of lineages. Before it used `soc` for this.

As `razzo` depends on `mbd`, it has to make the same transition. 

Currently, the [razzo Travis CI log](https://travis-ci.org/richelbilderbeek/razzo/jobs/451911430#L1617) and [razzo_project Travis CI log](https://travis-ci.org/richelbilderbeek/razzo_project/builds/452255647#L1438) fail due to

``` 
unused argument (n_0 = n_0)
unused argument (soc = n_0)
```

**Comment by richelbilderbeek** [comment]
@Giappo: I suggest you fix this: it makes you aware of the impact of changing code that people depend on :+1:

**Comment by Giappo** [comment]
@richelbilderbeek you told me already. I got it. Now stop.

**Comment by richelbilderbeek** [comment]
Did I? Blimey, if I am start repeating myself... :older_man:

**Comment by Giappo** [comment]
I fixed it. Everything was fine but the package kept on calling one old version of mbd. Now it calls the new one, which was already working fine.
CLOSED

**Comment by richelbilderbeek** [comment]
Well done!
