### ISSUE TITLE
raz_collect_esses: collect ESSes

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#78]
From the data, we'll need to collect the effective sample sizes of all runs. `raz_collect_esses` collects all ESSes and returns these as a tidy data frame.

A sneak-preview of the tests:

```r
context("test-raz_collect_esses")

test_that("use", {
  skip("TODO. Issue 78, #78")

  df <- raz_collect_esses(raz_get_path("razzo_project"))

  # Experimental parameters that vary
  expect_true("lambda" %in% names(df))
  expect_true("mu" %in% names(df))
  expect_true("nu" %in% names(df))
  expect_true("q" %in% names(df))
  expect_true("seed" %in% names(df))
  expect_true("site_model" %in% names(df))
  expect_true("clock_model" %in% names(df))

  # The collected effective sample sizes

  if (1 == 2) {
    # Here one can see the ESSes from one file
    example_log_file <- raz_get_path(
      "razzo_project/data/0.2-0.15-1-0.1/1/rln-gtr/mbd.log"
    )
    examples_esses <- tracerer::calc_esses(
      tracerer::parse_beast_log(example_log_file), sample_interval = 1000
    )
  }
  # I (@richelbilderbeek) suggest to take the ESS of the likelihood,
  # and that one only. We'll see if that idea changes in the future.
  expect_true("ess_likelihood" %in% names(df))

  # Data must be tidy
  expect_true(is.factor(df$clock_model))
  expect_true(is.factor(df$site_model))

})

test_that("abuse", {
  skip("TODO. Issue 78, #78")
  expect_error(
    raz_collect_esses("nonsense"),
    "'folder_name' must end with 'razzo_project'"
  )
})
```

**Comment by richelbilderbeek** [comment]
Depends on #80 being solved.

**Comment by richelbilderbeek** [comment]
Assign myself to remind myself that I first need to solve #80 before assigning this to Giovanni.

**Comment by richelbilderbeek** [comment]
@Giappo: this Issue if open to being done!

**Comment by Giappo** [comment]
@richelbilderbeek 
ok, so I understood that the best way is to use tracerer to do so.
I am trying to run this code:

paths <- raz_get_settings_paths(project_folder_name) # nolint internal function
  parameters <- raz_open_parameters_file(file.path(paths[1], "parameters.csv")) # nolint internal function
  x <- file.path(paths[1], "mbd.log")
  y <- file.path(paths[1], "bd.log")
  x2 <- read.table(x)
  y2 <- read.table(y)

  # Remove burn-ins
  estimates <- tracerer::remove_burn_ins(
    x2,
    burn_in_fraction = 0.1
  )

  # Calculate the effective sample sizes of all parameter estimates
  esses <- tracerer::calc_esses(
    estimates,
    sample_interval = parameters$sample_interval
  )

And I get the following error:
"object 'Sample' not found"

Apparently this information is not provided in the log files. Where do I get it then?

**Comment by Giappo** [comment]
Ok, so I opened tracerer::calc_esses and inside I find this:

# Remove warning: no visible binding for global variable 'Sample'
  Sample <- NULL; rm(Sample) # nolint use uppercase variable name just like BEAST2
  # Remove the Sample column from the dataframe
  traces <- subset(traces, select = -c(Sample )) # nolint use uppercase variable name just like BEAST2

How can it use the variable Sample if it gets remove in the previous line?
Is it normal?

**Comment by Giappo** [comment]
Ok, nevermind. I got what you meant. I created this function and create_esses_file.
Waiting for travis to be travis, aka a bitch.

**Comment by richelbilderbeek** [comment]
Well done!
