### ISSUE TITLE
Create figure 1

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#79]
The nLTT statistics are collected in #84. These must be visualized in some way.

In the tests I suggest to let a function called `raz_create_fig_1` return such a plot:

```r
context("test-raz_create_fig_1")

test_that("use", {
  skip("TODO. Issue 79, #79")

  # Should return plot
  plot <- raz_creat_fig_1(raz_get_path("razzo_project"))
  expect_true(class(plot) == c("gg", "ggplot"))
})

test_that("abuse", {
  skip("TODO. Issue 79, #79")
  expect_error(
    raz_creat_fig_1("nonsense"),
    "'folder_name' must end with 'razzo_project'"
  )
})
```

I suggest the plot to look like this:

![razzo_fig](https://user-images.githubusercontent.com/2098230/48408669-28987680-e73a-11e8-8d85-3fb46694a757.png)

Goal of the plot is to see if any setup gives completely wrong values.

**Comment by Giappo** [comment]
We have an output. See if you like it. Just run test-raz_create_fig_1

**Comment by richelbilderbeek** [comment]
Well done!

Closing Issue.
