### ISSUE TITLE
Create and save figure 1 to file

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#85]
After #79 ('Create figure 1'), there needs be a script-friendly function to save the figure to a file. 

Target path should be `razzo_project/results/fig_1.png`, as agreed on. If the file should be a PNG or SVG or both is up for discussion in the 'Launch' phase.

Sneak-preview of the tests:

```r
context("test-raz_create_fig_1_file")

test_that("use", {
  skip("TODO. Issue 85, #85")

  # Should create 'results/fig_1.png'
  filename <- raz_creat_fig_1_file(raz_get_path("razzo_project"))

  # File should be created
  expect_true(file.exists(filename))

  # OK: filename must end with 'fig_1.png'
  testthat::expect_true(
    length(
      grep(
        pattern = "figure_1\\.png$", filename, perl = TRUE, value = TRUE
      )
    ) > 0
  )
  # OK: should be in razzo_project/results folder
  # Use ..? to indicate one or two back- or normal slashes
  testthat::expect_true(
    length(
      grep(
        pattern = "razzo_project..?results..?",
        filename, perl = TRUE, value = TRUE
      )
    ) > 0
  )

})

test_that("abuse", {
  skip("TODO. Issue 85, #85")
  expect_error(
    raz_creat_fig_1_file("nonsense"),
    "'folder_name' must end with 'razzo_project'"
  )
})
```

**Comment by Giappo** [comment]
Added the raz_create_fig_1_file. You can find the file in "razzo_project/results_folder". Hope it looks fine.

**Comment by richelbilderbeek** [comment]
@Giappo: this is good enough, well done :+1:! 

I will remove the file from `inst/extdata` though, as it should not be there... :rainbow: 

But one can upload files at Issues. Look how pretty: :rabbit: 

![figure_1](https://user-images.githubusercontent.com/2098230/48773735-8e4faa00-ecc8-11e8-8891-ca4d1c356c3f.png)
