### ISSUE TITLE
nltt statistics have different number of trees for each settings

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#90]
nltt statistics have different number of trees for each settings. I don't know if this could actually be a problem but these numbers can differ a lot. For example for seed == 1 we get posterior with more than 100 nltt values. With seed == 2 they are all less than 100. You can use raz_collect_nltt_stats to verify this.

**Comment by richelbilderbeek** [comment]
Hmm, problem is probably at `tracerer`. 

I suggest to use NAs for missing values. Limiting the collected nLTTs to the bare minimum of 3 would be also good enough for 'Ignition'.

Well spotted!

**Comment by richelbilderbeek** [comment]
A more lenient approach: wait until tomorrow, as then I've probably fixed it  :grin:

**Comment by richelbilderbeek** [comment]
AFAICS, I've fixed it, on my `razzo` branch, will merge to `develop` soon. Had to change `tracerer`, so do:

```
devtools::install_github("richelbilderbeek/tracerer")
```

**Comment by richelbilderbeek** [comment]
Fun consequence: Giovanni will be able to do the normal BEAST2 runs. Only the NS runs -which will be different runs!- will remain out of his reach :milky_way:

**Comment by richelbilderbeek** [comment]
This Issue was due that `babette` either estimates biological parameters xor estimates a marginal likelihood. Seperating these two is done in seperate Issues.

Closing this one.
