### ISSUE TITLE
Use create_filename functions or remove them

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#98]
In the file "raz_create_filenames.R" we have 4 functions that are supposed to be used to create filenames for both "bd" and "mbd" alignments and tree.
These functions are actually never used.
We have to decide if we really need them or not.
If yes let's implement them every time we need to create a file name and then let's add tests.
If not (which is the simpler option) let's just remove them and their test (which now are just stubs).

**Comment by richelbilderbeek** [comment]
I would also vote to remove it. The function has had its place and now its time for it to go :christmas_tree: :santa:

**Comment by richelbilderbeek** [comment]
@Giappo: I vote to remove it. What is your vote?
